// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/vectradb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_vectradb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{0}
}

type StatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_proto_vectradb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StatusResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Collections
type CreateCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionReq) Reset() {
	*x = CreateCollectionReq{}
	mi := &file_proto_vectradb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionReq) ProtoMessage() {}

func (x *CreateCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionReq.ProtoReflect.Descriptor instead.
func (*CreateCollectionReq) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCollectionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionReq) Reset() {
	*x = DropCollectionReq{}
	mi := &file_proto_vectradb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionReq) ProtoMessage() {}

func (x *DropCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionReq.ProtoReflect.Descriptor instead.
func (*DropCollectionReq) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{3}
}

func (x *DropCollectionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCollectionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []string               `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResp) Reset() {
	*x = ListCollectionsResp{}
	mi := &file_proto_vectradb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResp) ProtoMessage() {}

func (x *ListCollectionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResp.ProtoReflect.Descriptor instead.
func (*ListCollectionsResp) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{4}
}

func (x *ListCollectionsResp) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

// Records
type InsertReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertReq) Reset() {
	*x = InsertReq{}
	mi := &file_proto_vectradb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertReq) ProtoMessage() {}

func (x *InsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertReq.ProtoReflect.Descriptor instead.
func (*InsertReq) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{5}
}

func (x *InsertReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertReq) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type BatchInsertReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Records       []*InsertRecord        `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertReq) Reset() {
	*x = BatchInsertReq{}
	mi := &file_proto_vectradb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertReq) ProtoMessage() {}

func (x *BatchInsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertReq.ProtoReflect.Descriptor instead.
func (*BatchInsertReq) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{6}
}

func (x *BatchInsertReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BatchInsertReq) GetRecords() []*InsertRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type InsertRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRecord) Reset() {
	*x = InsertRecord{}
	mi := &file_proto_vectradb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRecord) ProtoMessage() {}

func (x *InsertRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRecord.ProtoReflect.Descriptor instead.
func (*InsertRecord) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{7}
}

func (x *InsertRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertRecord) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertRecord) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type BatchInsertResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertResp) Reset() {
	*x = BatchInsertResp{}
	mi := &file_proto_vectradb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertResp) ProtoMessage() {}

func (x *BatchInsertResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertResp.ProtoReflect.Descriptor instead.
func (*BatchInsertResp) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchInsertResp) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *BatchInsertResp) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchInsertResp) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_proto_vectradb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int32                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_proto_vectradb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResp) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteResp) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *DeleteResp) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_proto_vectradb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{11}
}

func (x *SearchReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_proto_vectradb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResp) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_vectradb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// Text chunking
type ChunkTextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`                                   // "merged" (default), "paragraph", "sentence"
	MinChunkChars int32                  `protobuf:"varint,3,opt,name=min_chunk_chars,json=minChunkChars,proto3" json:"min_chunk_chars,omitempty"` // default: 80
	MaxChunkChars int32                  `protobuf:"varint,4,opt,name=max_chunk_chars,json=maxChunkChars,proto3" json:"max_chunk_chars,omitempty"` // default: 600
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkTextReq) Reset() {
	*x = ChunkTextReq{}
	mi := &file_proto_vectradb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkTextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkTextReq) ProtoMessage() {}

func (x *ChunkTextReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkTextReq.ProtoReflect.Descriptor instead.
func (*ChunkTextReq) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{14}
}

func (x *ChunkTextReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChunkTextReq) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ChunkTextReq) GetMinChunkChars() int32 {
	if x != nil {
		return x.MinChunkChars
	}
	return 0
}

func (x *ChunkTextReq) GetMaxChunkChars() int32 {
	if x != nil {
		return x.MaxChunkChars
	}
	return 0
}

type ChunkTextResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*TextChunk           `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkTextResp) Reset() {
	*x = ChunkTextResp{}
	mi := &file_proto_vectradb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkTextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkTextResp) ProtoMessage() {}

func (x *ChunkTextResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkTextResp.ProtoReflect.Descriptor instead.
func (*ChunkTextResp) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{15}
}

func (x *ChunkTextResp) GetChunks() []*TextChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type TextChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Chapter       int32                  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	CutType       string                 `protobuf:"bytes,5,opt,name=cut_type,json=cutType,proto3" json:"cut_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChunk) Reset() {
	*x = TextChunk{}
	mi := &file_proto_vectradb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChunk) ProtoMessage() {}

func (x *TextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChunk.ProtoReflect.Descriptor instead.
func (*TextChunk) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{16}
}

func (x *TextChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TextChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextChunk) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *TextChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *TextChunk) GetCutType() string {
	if x != nil {
		return x.CutType
	}
	return ""
}

// Info
type InfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimension     int32                  `protobuf:"varint,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Shards        int32                  `protobuf:"varint,2,opt,name=shards,proto3" json:"shards,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Collections   []string               `protobuf:"bytes,4,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResp) Reset() {
	*x = InfoResp{}
	mi := &file_proto_vectradb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResp) ProtoMessage() {}

func (x *InfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectradb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResp.ProtoReflect.Descriptor instead.
func (*InfoResp) Descriptor() ([]byte, []int) {
	return file_proto_vectradb_proto_rawDescGZIP(), []int{17}
}

func (x *InfoResp) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *InfoResp) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *InfoResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InfoResp) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

var File_proto_vectradb_proto protoreflect.FileDescriptor

const file_proto_vectradb_proto_rawDesc = "" +
	"\n" +
	"\x14proto/vectradb.proto\x12\vvectradb.v1\"\a\n" +
	"\x05Empty\"2\n" +
	"\n" +
	"StatusResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x13CreateCollectionReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x11DropCollectionReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x13ListCollectionsResp\x12 \n" +
	"\vcollections\x18\x01 \x03(\tR\vcollections\"x\n" +
	"\tInsertReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\"e\n" +
	"\x0eBatchInsertReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x123\n" +
	"\arecords\x18\x02 \x03(\v2\x19.vectradb.v1.InsertRecordR\arecords\"[\n" +
	"\fInsertRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\"]\n" +
	"\x0fBatchInsertResp\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"=\n" +
	"\tDeleteReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"V\n" +
	"\n" +
	"DeleteResp\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x05R\adeleted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"X\n" +
	"\tSearchReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"A\n" +
	"\n" +
	"SearchResp\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.vectradb.v1.SearchResultR\aresults\"Y\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\"\x8e\x01\n" +
	"\fChunkTextReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12&\n" +
	"\x0fmin_chunk_chars\x18\x03 \x01(\x05R\rminChunkChars\x12&\n" +
	"\x0fmax_chunk_chars\x18\x04 \x01(\x05R\rmaxChunkChars\"?\n" +
	"\rChunkTextResp\x12.\n" +
	"\x06chunks\x18\x01 \x03(\v2\x16.vectradb.v1.TextChunkR\x06chunks\"\x85\x01\n" +
	"\tTextChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\achapter\x18\x03 \x01(\x05R\achapter\x12\x1f\n" +
	"\vchunk_index\x18\x04 \x01(\x05R\n" +
	"chunkIndex\x12\x19\n" +
	"\bcut_type\x18\x05 \x01(\tR\acutType\"z\n" +
	"\bInfoResp\x12\x1c\n" +
	"\tdimension\x18\x01 \x01(\x05R\tdimension\x12\x16\n" +
	"\x06shards\x18\x02 \x01(\x05R\x06shards\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\vcollections\x18\x04 \x03(\tR\vcollections2\xe6\x04\n" +
	"\x0fVectraDBService\x12M\n" +
	"\x10CreateCollection\x12 .vectradb.v1.CreateCollectionReq\x1a\x17.vectradb.v1.StatusResp\x12I\n" +
	"\x0eDropCollection\x12\x1e.vectradb.v1.DropCollectionReq\x1a\x17.vectradb.v1.StatusResp\x12G\n" +
	"\x0fListCollections\x12\x12.vectradb.v1.Empty\x1a .vectradb.v1.ListCollectionsResp\x129\n" +
	"\x06Insert\x12\x16.vectradb.v1.InsertReq\x1a\x17.vectradb.v1.StatusResp\x12H\n" +
	"\vBatchInsert\x12\x1b.vectradb.v1.BatchInsertReq\x1a\x1c.vectradb.v1.BatchInsertResp\x129\n" +
	"\x06Delete\x12\x16.vectradb.v1.DeleteReq\x1a\x17.vectradb.v1.DeleteResp\x129\n" +
	"\x06Search\x12\x16.vectradb.v1.SearchReq\x1a\x17.vectradb.v1.SearchResp\x12B\n" +
	"\tChunkText\x12\x19.vectradb.v1.ChunkTextReq\x1a\x1a.vectradb.v1.ChunkTextResp\x121\n" +
	"\x04Info\x12\x12.vectradb.v1.Empty\x1a\x15.vectradb.v1.InfoRespB(Z&github.com/rupamthxt/vectradb/proto/pbb\x06proto3"

var (
	file_proto_vectradb_proto_rawDescOnce sync.Once
	file_proto_vectradb_proto_rawDescData []byte
)

func file_proto_vectradb_proto_rawDescGZIP() []byte {
	file_proto_vectradb_proto_rawDescOnce.Do(func() {
		file_proto_vectradb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vectradb_proto_rawDesc), len(file_proto_vectradb_proto_rawDesc)))
	})
	return file_proto_vectradb_proto_rawDescData
}

var file_proto_vectradb_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_vectradb_proto_goTypes = []any{
	(*Empty)(nil),               // 0: vectradb.v1.Empty
	(*StatusResp)(nil),          // 1: vectradb.v1.StatusResp
	(*CreateCollectionReq)(nil), // 2: vectradb.v1.CreateCollectionReq
	(*DropCollectionReq)(nil),   // 3: vectradb.v1.DropCollectionReq
	(*ListCollectionsResp)(nil), // 4: vectradb.v1.ListCollectionsResp
	(*InsertReq)(nil),           // 5: vectradb.v1.InsertReq
	(*BatchInsertReq)(nil),      // 6: vectradb.v1.BatchInsertReq
	(*InsertRecord)(nil),        // 7: vectradb.v1.InsertRecord
	(*BatchInsertResp)(nil),     // 8: vectradb.v1.BatchInsertResp
	(*DeleteReq)(nil),           // 9: vectradb.v1.DeleteReq
	(*DeleteResp)(nil),          // 10: vectradb.v1.DeleteResp
	(*SearchReq)(nil),           // 11: vectradb.v1.SearchReq
	(*SearchResp)(nil),          // 12: vectradb.v1.SearchResp
	(*SearchResult)(nil),        // 13: vectradb.v1.SearchResult
	(*ChunkTextReq)(nil),        // 14: vectradb.v1.ChunkTextReq
	(*ChunkTextResp)(nil),       // 15: vectradb.v1.ChunkTextResp
	(*TextChunk)(nil),           // 16: vectradb.v1.TextChunk
	(*InfoResp)(nil),            // 17: vectradb.v1.InfoResp
}
var file_proto_vectradb_proto_depIdxs = []int32{
	7,  // 0: vectradb.v1.BatchInsertReq.records:type_name -> vectradb.v1.InsertRecord
	13, // 1: vectradb.v1.SearchResp.results:type_name -> vectradb.v1.SearchResult
	16, // 2: vectradb.v1.ChunkTextResp.chunks:type_name -> vectradb.v1.TextChunk
	2,  // 3: vectradb.v1.VectraDBService.CreateCollection:input_type -> vectradb.v1.CreateCollectionReq
	3,  // 4: vectradb.v1.VectraDBService.DropCollection:input_type -> vectradb.v1.DropCollectionReq
	0,  // 5: vectradb.v1.VectraDBService.ListCollections:input_type -> vectradb.v1.Empty
	5,  // 6: vectradb.v1.VectraDBService.Insert:input_type -> vectradb.v1.InsertReq
	6,  // 7: vectradb.v1.VectraDBService.BatchInsert:input_type -> vectradb.v1.BatchInsertReq
	9,  // 8: vectradb.v1.VectraDBService.Delete:input_type -> vectradb.v1.DeleteReq
	11, // 9: vectradb.v1.VectraDBService.Search:input_type -> vectradb.v1.SearchReq
	14, // 10: vectradb.v1.VectraDBService.ChunkText:input_type -> vectradb.v1.ChunkTextReq
	0,  // 11: vectradb.v1.VectraDBService.Info:input_type -> vectradb.v1.Empty
	1,  // 12: vectradb.v1.VectraDBService.CreateCollection:output_type -> vectradb.v1.StatusResp
	1,  // 13: vectradb.v1.VectraDBService.DropCollection:output_type -> vectradb.v1.StatusResp
	4,  // 14: vectradb.v1.VectraDBService.ListCollections:output_type -> vectradb.v1.ListCollectionsResp
	1,  // 15: vectradb.v1.VectraDBService.Insert:output_type -> vectradb.v1.StatusResp
	8,  // 16: vectradb.v1.VectraDBService.BatchInsert:output_type -> vectradb.v1.BatchInsertResp
	10, // 17: vectradb.v1.VectraDBService.Delete:output_type -> vectradb.v1.DeleteResp
	12, // 18: vectradb.v1.VectraDBService.Search:output_type -> vectradb.v1.SearchResp
	15, // 19: vectradb.v1.VectraDBService.ChunkText:output_type -> vectradb.v1.ChunkTextResp
	17, // 20: vectradb.v1.VectraDBService.Info:output_type -> vectradb.v1.InfoResp
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_vectradb_proto_init() }
func file_proto_vectradb_proto_init() {
	if File_proto_vectradb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vectradb_proto_rawDesc), len(file_proto_vectradb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vectradb_proto_goTypes,
		DependencyIndexes: file_proto_vectradb_proto_depIdxs,
		MessageInfos:      file_proto_vectradb_proto_msgTypes,
	}.Build()
	File_proto_vectradb_proto = out.File
	file_proto_vectradb_proto_goTypes = nil
	file_proto_vectradb_proto_depIdxs = nil
}
