// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/vectradb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VectraDBService_CreateCollection_FullMethodName = "/vectradb.v1.VectraDBService/CreateCollection"
	VectraDBService_DropCollection_FullMethodName   = "/vectradb.v1.VectraDBService/DropCollection"
	VectraDBService_ListCollections_FullMethodName  = "/vectradb.v1.VectraDBService/ListCollections"
	VectraDBService_HasCollection_FullMethodName    = "/vectradb.v1.VectraDBService/HasCollection"
	VectraDBService_Insert_FullMethodName           = "/vectradb.v1.VectraDBService/Insert"
	VectraDBService_BatchInsert_FullMethodName      = "/vectradb.v1.VectraDBService/BatchInsert"
	VectraDBService_Delete_FullMethodName           = "/vectradb.v1.VectraDBService/Delete"
	VectraDBService_Search_FullMethodName           = "/vectradb.v1.VectraDBService/Search"
	VectraDBService_ChunkText_FullMethodName        = "/vectradb.v1.VectraDBService/ChunkText"
	VectraDBService_Info_FullMethodName             = "/vectradb.v1.VectraDBService/Info"
	VectraDBService_GetByID_FullMethodName          = "/vectradb.v1.VectraDBService/GetByID"
)

// VectraDBServiceClient is the client API for VectraDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectraDBServiceClient interface {
	// Collections
	CreateCollection(ctx context.Context, in *CreateCollectionReq, opts ...grpc.CallOption) (*StatusResp, error)
	DropCollection(ctx context.Context, in *DropCollectionReq, opts ...grpc.CallOption) (*StatusResp, error)
	ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResp, error)
	HasCollection(ctx context.Context, in *HasCollectionReq, opts ...grpc.CallOption) (*HasCollectionResp, error)
	// Records
	Insert(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*StatusResp, error)
	BatchInsert(ctx context.Context, in *BatchInsertReq, opts ...grpc.CallOption) (*BatchInsertResp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	// Text processing
	ChunkText(ctx context.Context, in *ChunkTextReq, opts ...grpc.CallOption) (*ChunkTextResp, error)
	// Info
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResp, error)
	// Record retrieval
	GetByID(ctx context.Context, in *GetByIDReq, opts ...grpc.CallOption) (*GetByIDResp, error)
}

type vectraDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectraDBServiceClient(cc grpc.ClientConnInterface) VectraDBServiceClient {
	return &vectraDBServiceClient{cc}
}

func (c *vectraDBServiceClient) CreateCollection(ctx context.Context, in *CreateCollectionReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, VectraDBService_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) DropCollection(ctx context.Context, in *DropCollectionReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, VectraDBService_DropCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResp)
	err := c.cc.Invoke(ctx, VectraDBService_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) HasCollection(ctx context.Context, in *HasCollectionReq, opts ...grpc.CallOption) (*HasCollectionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasCollectionResp)
	err := c.cc.Invoke(ctx, VectraDBService_HasCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) Insert(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, VectraDBService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) BatchInsert(ctx context.Context, in *BatchInsertReq, opts ...grpc.CallOption) (*BatchInsertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInsertResp)
	err := c.cc.Invoke(ctx, VectraDBService_BatchInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, VectraDBService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, VectraDBService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) ChunkText(ctx context.Context, in *ChunkTextReq, opts ...grpc.CallOption) (*ChunkTextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkTextResp)
	err := c.cc.Invoke(ctx, VectraDBService_ChunkText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResp)
	err := c.cc.Invoke(ctx, VectraDBService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectraDBServiceClient) GetByID(ctx context.Context, in *GetByIDReq, opts ...grpc.CallOption) (*GetByIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByIDResp)
	err := c.cc.Invoke(ctx, VectraDBService_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectraDBServiceServer is the server API for VectraDBService service.
// All implementations must embed UnimplementedVectraDBServiceServer
// for forward compatibility.
type VectraDBServiceServer interface {
	// Collections
	CreateCollection(context.Context, *CreateCollectionReq) (*StatusResp, error)
	DropCollection(context.Context, *DropCollectionReq) (*StatusResp, error)
	ListCollections(context.Context, *Empty) (*ListCollectionsResp, error)
	HasCollection(context.Context, *HasCollectionReq) (*HasCollectionResp, error)
	// Records
	Insert(context.Context, *InsertReq) (*StatusResp, error)
	BatchInsert(context.Context, *BatchInsertReq) (*BatchInsertResp, error)
	Delete(context.Context, *DeleteReq) (*DeleteResp, error)
	Search(context.Context, *SearchReq) (*SearchResp, error)
	// Text processing
	ChunkText(context.Context, *ChunkTextReq) (*ChunkTextResp, error)
	// Info
	Info(context.Context, *Empty) (*InfoResp, error)
	// Record retrieval
	GetByID(context.Context, *GetByIDReq) (*GetByIDResp, error)
	mustEmbedUnimplementedVectraDBServiceServer()
}

// UnimplementedVectraDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectraDBServiceServer struct{}

func (UnimplementedVectraDBServiceServer) CreateCollection(context.Context, *CreateCollectionReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedVectraDBServiceServer) DropCollection(context.Context, *DropCollectionReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DropCollection not implemented")
}
func (UnimplementedVectraDBServiceServer) ListCollections(context.Context, *Empty) (*ListCollectionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedVectraDBServiceServer) HasCollection(context.Context, *HasCollectionReq) (*HasCollectionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HasCollection not implemented")
}
func (UnimplementedVectraDBServiceServer) Insert(context.Context, *InsertReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedVectraDBServiceServer) BatchInsert(context.Context, *BatchInsertReq) (*BatchInsertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInsert not implemented")
}
func (UnimplementedVectraDBServiceServer) Delete(context.Context, *DeleteReq) (*DeleteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVectraDBServiceServer) Search(context.Context, *SearchReq) (*SearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedVectraDBServiceServer) ChunkText(context.Context, *ChunkTextReq) (*ChunkTextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkText not implemented")
}
func (UnimplementedVectraDBServiceServer) Info(context.Context, *Empty) (*InfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedVectraDBServiceServer) GetByID(context.Context, *GetByIDReq) (*GetByIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedVectraDBServiceServer) mustEmbedUnimplementedVectraDBServiceServer() {}
func (UnimplementedVectraDBServiceServer) testEmbeddedByValue()                         {}

// UnsafeVectraDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectraDBServiceServer will
// result in compilation errors.
type UnsafeVectraDBServiceServer interface {
	mustEmbedUnimplementedVectraDBServiceServer()
}

func RegisterVectraDBServiceServer(s grpc.ServiceRegistrar, srv VectraDBServiceServer) {
	// If the following call panics, it indicates UnimplementedVectraDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectraDBService_ServiceDesc, srv)
}

func _VectraDBService_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).CreateCollection(ctx, req.(*CreateCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_DropCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).DropCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_DropCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).DropCollection(ctx, req.(*DropCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).ListCollections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_HasCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).HasCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_HasCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).HasCollection(ctx, req.(*HasCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).Insert(ctx, req.(*InsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_BatchInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).BatchInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_BatchInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).BatchInsert(ctx, req.(*BatchInsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_ChunkText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkTextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).ChunkText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_ChunkText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).ChunkText(ctx, req.(*ChunkTextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectraDBService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectraDBServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectraDBService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectraDBServiceServer).GetByID(ctx, req.(*GetByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VectraDBService_ServiceDesc is the grpc.ServiceDesc for VectraDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectraDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vectradb.v1.VectraDBService",
	HandlerType: (*VectraDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _VectraDBService_CreateCollection_Handler,
		},
		{
			MethodName: "DropCollection",
			Handler:    _VectraDBService_DropCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _VectraDBService_ListCollections_Handler,
		},
		{
			MethodName: "HasCollection",
			Handler:    _VectraDBService_HasCollection_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _VectraDBService_Insert_Handler,
		},
		{
			MethodName: "BatchInsert",
			Handler:    _VectraDBService_BatchInsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VectraDBService_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _VectraDBService_Search_Handler,
		},
		{
			MethodName: "ChunkText",
			Handler:    _VectraDBService_ChunkText_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _VectraDBService_Info_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _VectraDBService_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vectradb.proto",
}
