// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/cognevra.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CognevraService_CreateCollection_FullMethodName = "/cognevra.v1.CognevraService/CreateCollection"
	CognevraService_DropCollection_FullMethodName   = "/cognevra.v1.CognevraService/DropCollection"
	CognevraService_ListCollections_FullMethodName  = "/cognevra.v1.CognevraService/ListCollections"
	CognevraService_HasCollection_FullMethodName    = "/cognevra.v1.CognevraService/HasCollection"
	CognevraService_Insert_FullMethodName           = "/cognevra.v1.CognevraService/Insert"
	CognevraService_BatchInsert_FullMethodName      = "/cognevra.v1.CognevraService/BatchInsert"
	CognevraService_Delete_FullMethodName           = "/cognevra.v1.CognevraService/Delete"
	CognevraService_Search_FullMethodName           = "/cognevra.v1.CognevraService/Search"
	CognevraService_ChunkText_FullMethodName        = "/cognevra.v1.CognevraService/ChunkText"
	CognevraService_Info_FullMethodName             = "/cognevra.v1.CognevraService/Info"
	CognevraService_GetByID_FullMethodName          = "/cognevra.v1.CognevraService/GetByID"
)

// CognevraServiceClient is the client API for CognevraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CognevraServiceClient interface {
	// Collections
	CreateCollection(ctx context.Context, in *CreateCollectionReq, opts ...grpc.CallOption) (*StatusResp, error)
	DropCollection(ctx context.Context, in *DropCollectionReq, opts ...grpc.CallOption) (*StatusResp, error)
	ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResp, error)
	HasCollection(ctx context.Context, in *HasCollectionReq, opts ...grpc.CallOption) (*HasCollectionResp, error)
	// Records
	Insert(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*StatusResp, error)
	BatchInsert(ctx context.Context, in *BatchInsertReq, opts ...grpc.CallOption) (*BatchInsertResp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	// Text processing
	ChunkText(ctx context.Context, in *ChunkTextReq, opts ...grpc.CallOption) (*ChunkTextResp, error)
	// Info
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResp, error)
	// Record retrieval
	GetByID(ctx context.Context, in *GetByIDReq, opts ...grpc.CallOption) (*GetByIDResp, error)
}

type cognevraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCognevraServiceClient(cc grpc.ClientConnInterface) CognevraServiceClient {
	return &cognevraServiceClient{cc}
}

func (c *cognevraServiceClient) CreateCollection(ctx context.Context, in *CreateCollectionReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, CognevraService_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) DropCollection(ctx context.Context, in *DropCollectionReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, CognevraService_DropCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResp)
	err := c.cc.Invoke(ctx, CognevraService_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) HasCollection(ctx context.Context, in *HasCollectionReq, opts ...grpc.CallOption) (*HasCollectionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasCollectionResp)
	err := c.cc.Invoke(ctx, CognevraService_HasCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) Insert(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, CognevraService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) BatchInsert(ctx context.Context, in *BatchInsertReq, opts ...grpc.CallOption) (*BatchInsertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInsertResp)
	err := c.cc.Invoke(ctx, CognevraService_BatchInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, CognevraService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, CognevraService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) ChunkText(ctx context.Context, in *ChunkTextReq, opts ...grpc.CallOption) (*ChunkTextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkTextResp)
	err := c.cc.Invoke(ctx, CognevraService_ChunkText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResp)
	err := c.cc.Invoke(ctx, CognevraService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) GetByID(ctx context.Context, in *GetByIDReq, opts ...grpc.CallOption) (*GetByIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByIDResp)
	err := c.cc.Invoke(ctx, CognevraService_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CognevraServiceServer is the server API for CognevraService service.
// All implementations must embed UnimplementedCognevraServiceServer
// for forward compatibility.
type CognevraServiceServer interface {
	// Collections
	CreateCollection(context.Context, *CreateCollectionReq) (*StatusResp, error)
	DropCollection(context.Context, *DropCollectionReq) (*StatusResp, error)
	ListCollections(context.Context, *Empty) (*ListCollectionsResp, error)
	HasCollection(context.Context, *HasCollectionReq) (*HasCollectionResp, error)
	// Records
	Insert(context.Context, *InsertReq) (*StatusResp, error)
	BatchInsert(context.Context, *BatchInsertReq) (*BatchInsertResp, error)
	Delete(context.Context, *DeleteReq) (*DeleteResp, error)
	Search(context.Context, *SearchReq) (*SearchResp, error)
	// Text processing
	ChunkText(context.Context, *ChunkTextReq) (*ChunkTextResp, error)
	// Info
	Info(context.Context, *Empty) (*InfoResp, error)
	// Record retrieval
	GetByID(context.Context, *GetByIDReq) (*GetByIDResp, error)
	mustEmbedUnimplementedCognevraServiceServer()
}

// UnimplementedCognevraServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCognevraServiceServer struct{}

func (UnimplementedCognevraServiceServer) CreateCollection(context.Context, *CreateCollectionReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedCognevraServiceServer) DropCollection(context.Context, *DropCollectionReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DropCollection not implemented")
}
func (UnimplementedCognevraServiceServer) ListCollections(context.Context, *Empty) (*ListCollectionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedCognevraServiceServer) HasCollection(context.Context, *HasCollectionReq) (*HasCollectionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HasCollection not implemented")
}
func (UnimplementedCognevraServiceServer) Insert(context.Context, *InsertReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedCognevraServiceServer) BatchInsert(context.Context, *BatchInsertReq) (*BatchInsertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInsert not implemented")
}
func (UnimplementedCognevraServiceServer) Delete(context.Context, *DeleteReq) (*DeleteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCognevraServiceServer) Search(context.Context, *SearchReq) (*SearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedCognevraServiceServer) ChunkText(context.Context, *ChunkTextReq) (*ChunkTextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkText not implemented")
}
func (UnimplementedCognevraServiceServer) Info(context.Context, *Empty) (*InfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedCognevraServiceServer) GetByID(context.Context, *GetByIDReq) (*GetByIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedCognevraServiceServer) mustEmbedUnimplementedCognevraServiceServer() {}
func (UnimplementedCognevraServiceServer) testEmbeddedByValue()                         {}

// UnsafeCognevraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CognevraServiceServer will
// result in compilation errors.
type UnsafeCognevraServiceServer interface {
	mustEmbedUnimplementedCognevraServiceServer()
}

func RegisterCognevraServiceServer(s grpc.ServiceRegistrar, srv CognevraServiceServer) {
	// If the following call panics, it indicates UnimplementedCognevraServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CognevraService_ServiceDesc, srv)
}

func _CognevraService_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).CreateCollection(ctx, req.(*CreateCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_DropCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).DropCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_DropCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).DropCollection(ctx, req.(*DropCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).ListCollections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_HasCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).HasCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_HasCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).HasCollection(ctx, req.(*HasCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).Insert(ctx, req.(*InsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_BatchInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).BatchInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_BatchInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).BatchInsert(ctx, req.(*BatchInsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_ChunkText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkTextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).ChunkText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_ChunkText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).ChunkText(ctx, req.(*ChunkTextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).GetByID(ctx, req.(*GetByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CognevraService_ServiceDesc is the grpc.ServiceDesc for CognevraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CognevraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cognevra.v1.CognevraService",
	HandlerType: (*CognevraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _CognevraService_CreateCollection_Handler,
		},
		{
			MethodName: "DropCollection",
			Handler:    _CognevraService_DropCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _CognevraService_ListCollections_Handler,
		},
		{
			MethodName: "HasCollection",
			Handler:    _CognevraService_HasCollection_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _CognevraService_Insert_Handler,
		},
		{
			MethodName: "BatchInsert",
			Handler:    _CognevraService_BatchInsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CognevraService_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _CognevraService_Search_Handler,
		},
		{
			MethodName: "ChunkText",
			Handler:    _CognevraService_ChunkText_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _CognevraService_Info_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _CognevraService_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cognevra.proto",
}
