// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/cognevra.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_cognevra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{0}
}

type StatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_proto_cognevra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StatusResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Collections
type CreateCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionReq) Reset() {
	*x = CreateCollectionReq{}
	mi := &file_proto_cognevra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionReq) ProtoMessage() {}

func (x *CreateCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionReq.ProtoReflect.Descriptor instead.
func (*CreateCollectionReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCollectionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionReq) Reset() {
	*x = DropCollectionReq{}
	mi := &file_proto_cognevra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionReq) ProtoMessage() {}

func (x *DropCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionReq.ProtoReflect.Descriptor instead.
func (*DropCollectionReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{3}
}

func (x *DropCollectionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCollectionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []string               `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResp) Reset() {
	*x = ListCollectionsResp{}
	mi := &file_proto_cognevra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResp) ProtoMessage() {}

func (x *ListCollectionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResp.ProtoReflect.Descriptor instead.
func (*ListCollectionsResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{4}
}

func (x *ListCollectionsResp) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

type HasCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasCollectionReq) Reset() {
	*x = HasCollectionReq{}
	mi := &file_proto_cognevra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasCollectionReq) ProtoMessage() {}

func (x *HasCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasCollectionReq.ProtoReflect.Descriptor instead.
func (*HasCollectionReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{5}
}

func (x *HasCollectionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HasCollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasCollectionResp) Reset() {
	*x = HasCollectionResp{}
	mi := &file_proto_cognevra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasCollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasCollectionResp) ProtoMessage() {}

func (x *HasCollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasCollectionResp.ProtoReflect.Descriptor instead.
func (*HasCollectionResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{6}
}

func (x *HasCollectionResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// Records
type InsertReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertReq) Reset() {
	*x = InsertReq{}
	mi := &file_proto_cognevra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertReq) ProtoMessage() {}

func (x *InsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertReq.ProtoReflect.Descriptor instead.
func (*InsertReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{7}
}

func (x *InsertReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertReq) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type BatchInsertReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Records       []*InsertRecord        `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertReq) Reset() {
	*x = BatchInsertReq{}
	mi := &file_proto_cognevra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertReq) ProtoMessage() {}

func (x *BatchInsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertReq.ProtoReflect.Descriptor instead.
func (*BatchInsertReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{8}
}

func (x *BatchInsertReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BatchInsertReq) GetRecords() []*InsertRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type InsertRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRecord) Reset() {
	*x = InsertRecord{}
	mi := &file_proto_cognevra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRecord) ProtoMessage() {}

func (x *InsertRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRecord.ProtoReflect.Descriptor instead.
func (*InsertRecord) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{9}
}

func (x *InsertRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertRecord) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertRecord) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type BatchInsertResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertResp) Reset() {
	*x = BatchInsertResp{}
	mi := &file_proto_cognevra_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertResp) ProtoMessage() {}

func (x *BatchInsertResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertResp.ProtoReflect.Descriptor instead.
func (*BatchInsertResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{10}
}

func (x *BatchInsertResp) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *BatchInsertResp) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchInsertResp) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_proto_cognevra_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int32                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_proto_cognevra_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResp) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteResp) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *DeleteResp) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_proto_cognevra_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{13}
}

func (x *SearchReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_proto_cognevra_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{14}
}

func (x *SearchResp) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_cognevra_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{15}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// Record retrieval by ID
type GetByIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDReq) Reset() {
	*x = GetByIDReq{}
	mi := &file_proto_cognevra_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDReq) ProtoMessage() {}

func (x *GetByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDReq.ProtoReflect.Descriptor instead.
func (*GetByIDReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{16}
}

func (x *GetByIDReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetByIDReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetByIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*RecordEntry         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDResp) Reset() {
	*x = GetByIDResp{}
	mi := &file_proto_cognevra_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDResp) ProtoMessage() {}

func (x *GetByIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDResp.ProtoReflect.Descriptor instead.
func (*GetByIDResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{17}
}

func (x *GetByIDResp) GetRecords() []*RecordEntry {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecordEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,2,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Vector        []float32              `protobuf:"fixed32,4,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEntry) Reset() {
	*x = RecordEntry{}
	mi := &file_proto_cognevra_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEntry) ProtoMessage() {}

func (x *RecordEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEntry.ProtoReflect.Descriptor instead.
func (*RecordEntry) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{18}
}

func (x *RecordEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordEntry) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *RecordEntry) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RecordEntry) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

// Text chunking
type ChunkTextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`                                   // "merged" (default), "paragraph", "sentence"
	MinChunkChars int32                  `protobuf:"varint,3,opt,name=min_chunk_chars,json=minChunkChars,proto3" json:"min_chunk_chars,omitempty"` // default: 80
	MaxChunkChars int32                  `protobuf:"varint,4,opt,name=max_chunk_chars,json=maxChunkChars,proto3" json:"max_chunk_chars,omitempty"` // default: 600
	DocumentId    string                 `protobuf:"bytes,5,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`             // NEW: for deterministic UUID5 chunk IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkTextReq) Reset() {
	*x = ChunkTextReq{}
	mi := &file_proto_cognevra_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkTextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkTextReq) ProtoMessage() {}

func (x *ChunkTextReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkTextReq.ProtoReflect.Descriptor instead.
func (*ChunkTextReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{19}
}

func (x *ChunkTextReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChunkTextReq) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ChunkTextReq) GetMinChunkChars() int32 {
	if x != nil {
		return x.MinChunkChars
	}
	return 0
}

func (x *ChunkTextReq) GetMaxChunkChars() int32 {
	if x != nil {
		return x.MaxChunkChars
	}
	return 0
}

func (x *ChunkTextReq) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ChunkTextResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*TextChunk           `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkTextResp) Reset() {
	*x = ChunkTextResp{}
	mi := &file_proto_cognevra_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkTextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkTextResp) ProtoMessage() {}

func (x *ChunkTextResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkTextResp.ProtoReflect.Descriptor instead.
func (*ChunkTextResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{20}
}

func (x *ChunkTextResp) GetChunks() []*TextChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type TextChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Chapter       int32                  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	CutType       string                 `protobuf:"bytes,5,opt,name=cut_type,json=cutType,proto3" json:"cut_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChunk) Reset() {
	*x = TextChunk{}
	mi := &file_proto_cognevra_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChunk) ProtoMessage() {}

func (x *TextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChunk.ProtoReflect.Descriptor instead.
func (*TextChunk) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{21}
}

func (x *TextChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TextChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextChunk) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *TextChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *TextChunk) GetCutType() string {
	if x != nil {
		return x.CutType
	}
	return ""
}

// Info
type InfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimension     int32                  `protobuf:"varint,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Shards        int32                  `protobuf:"varint,2,opt,name=shards,proto3" json:"shards,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Collections   []string               `protobuf:"bytes,4,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResp) Reset() {
	*x = InfoResp{}
	mi := &file_proto_cognevra_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResp) ProtoMessage() {}

func (x *InfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResp.ProtoReflect.Descriptor instead.
func (*InfoResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{22}
}

func (x *InfoResp) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *InfoResp) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *InfoResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InfoResp) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

// Triplet processing
type ProcessTripletsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTripletsReq) Reset() {
	*x = ProcessTripletsReq{}
	mi := &file_proto_cognevra_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTripletsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTripletsReq) ProtoMessage() {}

func (x *ProcessTripletsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTripletsReq.ProtoReflect.Descriptor instead.
func (*ProcessTripletsReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{23}
}

func (x *ProcessTripletsReq) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ProcessTripletsReq) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GraphNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_proto_cognevra_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{24}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GraphEdge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceId         string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId         string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	RelationshipName string                 `protobuf:"bytes,3,opt,name=relationship_name,json=relationshipName,proto3" json:"relationship_name,omitempty"`
	EdgeText         string                 `protobuf:"bytes,4,opt,name=edge_text,json=edgeText,proto3" json:"edge_text,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_proto_cognevra_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{25}
}

func (x *GraphEdge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *GraphEdge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GraphEdge) GetRelationshipName() string {
	if x != nil {
		return x.RelationshipName
	}
	return ""
}

func (x *GraphEdge) GetEdgeText() string {
	if x != nil {
		return x.EdgeText
	}
	return ""
}

type TripletResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromNodeId    string                 `protobuf:"bytes,2,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId      string                 `protobuf:"bytes,3,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripletResult) Reset() {
	*x = TripletResult{}
	mi := &file_proto_cognevra_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripletResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripletResult) ProtoMessage() {}

func (x *TripletResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripletResult.ProtoReflect.Descriptor instead.
func (*TripletResult) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{26}
}

func (x *TripletResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TripletResult) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *TripletResult) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *TripletResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ProcessTripletsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triplets      []*TripletResult       `protobuf:"bytes,1,rep,name=triplets,proto3" json:"triplets,omitempty"`
	Created       int32                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Skipped       int32                  `protobuf:"varint,3,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTripletsResp) Reset() {
	*x = ProcessTripletsResp{}
	mi := &file_proto_cognevra_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTripletsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTripletsResp) ProtoMessage() {}

func (x *ProcessTripletsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTripletsResp.ProtoReflect.Descriptor instead.
func (*ProcessTripletsResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{27}
}

func (x *ProcessTripletsResp) GetTriplets() []*TripletResult {
	if x != nil {
		return x.Triplets
	}
	return nil
}

func (x *ProcessTripletsResp) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ProcessTripletsResp) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

// File I/O acceleration
type HashFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePaths     []string               `protobuf:"bytes,1,rep,name=file_paths,json=filePaths,proto3" json:"file_paths,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,2,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"` // goroutine pool size, default 8
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashFilesReq) Reset() {
	*x = HashFilesReq{}
	mi := &file_proto_cognevra_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashFilesReq) ProtoMessage() {}

func (x *HashFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashFilesReq.ProtoReflect.Descriptor instead.
func (*HashFilesReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{28}
}

func (x *HashFilesReq) GetFilePaths() []string {
	if x != nil {
		return x.FilePaths
	}
	return nil
}

func (x *HashFilesReq) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

type FileHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileHash) Reset() {
	*x = FileHash{}
	mi := &file_proto_cognevra_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHash) ProtoMessage() {}

func (x *FileHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHash.ProtoReflect.Descriptor instead.
func (*FileHash) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{29}
}

func (x *FileHash) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileHash) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FileHash) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileHash) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileHash) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HashFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FileHash            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashFilesResp) Reset() {
	*x = HashFilesResp{}
	mi := &file_proto_cognevra_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashFilesResp) ProtoMessage() {}

func (x *HashFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashFilesResp.ProtoReflect.Descriptor instead.
func (*HashFilesResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{30}
}

func (x *HashFilesResp) GetResults() []*FileHash {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListDirectoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootPath      string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Extensions    []string               `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"` // filter by extensions, empty = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryReq) Reset() {
	*x = ListDirectoryReq{}
	mi := &file_proto_cognevra_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryReq) ProtoMessage() {}

func (x *ListDirectoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryReq.ProtoReflect.Descriptor instead.
func (*ListDirectoryReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{31}
}

func (x *ListDirectoryReq) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *ListDirectoryReq) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *ListDirectoryReq) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type ListDirectoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePaths     []string               `protobuf:"bytes,1,rep,name=file_paths,json=filePaths,proto3" json:"file_paths,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryResp) Reset() {
	*x = ListDirectoryResp{}
	mi := &file_proto_cognevra_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResp) ProtoMessage() {}

func (x *ListDirectoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResp.ProtoReflect.Descriptor instead.
func (*ListDirectoryResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{32}
}

func (x *ListDirectoryResp) GetFilePaths() []string {
	if x != nil {
		return x.FilePaths
	}
	return nil
}

func (x *ListDirectoryResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Maintenance
type CompactResp struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CollectionsCompacted int32                  `protobuf:"varint,1,opt,name=collections_compacted,json=collectionsCompacted,proto3" json:"collections_compacted,omitempty"`
	Error                string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CompactResp) Reset() {
	*x = CompactResp{}
	mi := &file_proto_cognevra_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResp) ProtoMessage() {}

func (x *CompactResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResp.ProtoReflect.Descriptor instead.
func (*CompactResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{33}
}

func (x *CompactResp) GetCollectionsCompacted() int32 {
	if x != nil {
		return x.CollectionsCompacted
	}
	return 0
}

func (x *CompactResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Search aggregation
type AggregateSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*ScoredEdge          `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateSearchReq) Reset() {
	*x = AggregateSearchReq{}
	mi := &file_proto_cognevra_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateSearchReq) ProtoMessage() {}

func (x *AggregateSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateSearchReq.ProtoReflect.Descriptor instead.
func (*AggregateSearchReq) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{34}
}

func (x *AggregateSearchReq) GetEdges() []*ScoredEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *AggregateSearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type ScoredEdge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceId         string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceName       string                 `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceText       string                 `protobuf:"bytes,3,opt,name=source_text,json=sourceText,proto3" json:"source_text,omitempty"`
	SourceDistance   float32                `protobuf:"fixed32,4,opt,name=source_distance,json=sourceDistance,proto3" json:"source_distance,omitempty"`
	TargetId         string                 `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetName       string                 `protobuf:"bytes,6,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	TargetText       string                 `protobuf:"bytes,7,opt,name=target_text,json=targetText,proto3" json:"target_text,omitempty"`
	TargetDistance   float32                `protobuf:"fixed32,8,opt,name=target_distance,json=targetDistance,proto3" json:"target_distance,omitempty"`
	RelationshipName string                 `protobuf:"bytes,9,opt,name=relationship_name,json=relationshipName,proto3" json:"relationship_name,omitempty"`
	EdgeDistance     float32                `protobuf:"fixed32,10,opt,name=edge_distance,json=edgeDistance,proto3" json:"edge_distance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScoredEdge) Reset() {
	*x = ScoredEdge{}
	mi := &file_proto_cognevra_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredEdge) ProtoMessage() {}

func (x *ScoredEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredEdge.ProtoReflect.Descriptor instead.
func (*ScoredEdge) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{35}
}

func (x *ScoredEdge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ScoredEdge) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ScoredEdge) GetSourceText() string {
	if x != nil {
		return x.SourceText
	}
	return ""
}

func (x *ScoredEdge) GetSourceDistance() float32 {
	if x != nil {
		return x.SourceDistance
	}
	return 0
}

func (x *ScoredEdge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ScoredEdge) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *ScoredEdge) GetTargetText() string {
	if x != nil {
		return x.TargetText
	}
	return ""
}

func (x *ScoredEdge) GetTargetDistance() float32 {
	if x != nil {
		return x.TargetDistance
	}
	return 0
}

func (x *ScoredEdge) GetRelationshipName() string {
	if x != nil {
		return x.RelationshipName
	}
	return ""
}

func (x *ScoredEdge) GetEdgeDistance() float32 {
	if x != nil {
		return x.EdgeDistance
	}
	return 0
}

type AggregateSearchResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RankedEdges      []*RankedEdge          `protobuf:"bytes,1,rep,name=ranked_edges,json=rankedEdges,proto3" json:"ranked_edges,omitempty"`
	FormattedContext string                 `protobuf:"bytes,2,opt,name=formatted_context,json=formattedContext,proto3" json:"formatted_context,omitempty"`
	UniqueNodes      int32                  `protobuf:"varint,3,opt,name=unique_nodes,json=uniqueNodes,proto3" json:"unique_nodes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AggregateSearchResp) Reset() {
	*x = AggregateSearchResp{}
	mi := &file_proto_cognevra_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateSearchResp) ProtoMessage() {}

func (x *AggregateSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateSearchResp.ProtoReflect.Descriptor instead.
func (*AggregateSearchResp) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{36}
}

func (x *AggregateSearchResp) GetRankedEdges() []*RankedEdge {
	if x != nil {
		return x.RankedEdges
	}
	return nil
}

func (x *AggregateSearchResp) GetFormattedContext() string {
	if x != nil {
		return x.FormattedContext
	}
	return ""
}

func (x *AggregateSearchResp) GetUniqueNodes() int32 {
	if x != nil {
		return x.UniqueNodes
	}
	return 0
}

type RankedEdge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceId         string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceName       string                 `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	TargetId         string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetName       string                 `protobuf:"bytes,4,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	RelationshipName string                 `protobuf:"bytes,5,opt,name=relationship_name,json=relationshipName,proto3" json:"relationship_name,omitempty"`
	Score            float32                `protobuf:"fixed32,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RankedEdge) Reset() {
	*x = RankedEdge{}
	mi := &file_proto_cognevra_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedEdge) ProtoMessage() {}

func (x *RankedEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cognevra_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedEdge.ProtoReflect.Descriptor instead.
func (*RankedEdge) Descriptor() ([]byte, []int) {
	return file_proto_cognevra_proto_rawDescGZIP(), []int{37}
}

func (x *RankedEdge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *RankedEdge) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *RankedEdge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RankedEdge) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *RankedEdge) GetRelationshipName() string {
	if x != nil {
		return x.RelationshipName
	}
	return ""
}

func (x *RankedEdge) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_proto_cognevra_proto protoreflect.FileDescriptor

const file_proto_cognevra_proto_rawDesc = "" +
	"\n" +
	"\x14proto/cognevra.proto\x12\vcognevra.v1\"\a\n" +
	"\x05Empty\"2\n" +
	"\n" +
	"StatusResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x13CreateCollectionReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x11DropCollectionReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x13ListCollectionsResp\x12 \n" +
	"\vcollections\x18\x01 \x03(\tR\vcollections\"&\n" +
	"\x10HasCollectionReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x11HasCollectionResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"x\n" +
	"\tInsertReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\"e\n" +
	"\x0eBatchInsertReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x123\n" +
	"\arecords\x18\x02 \x03(\v2\x19.cognevra.v1.InsertRecordR\arecords\"[\n" +
	"\fInsertRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\"]\n" +
	"\x0fBatchInsertResp\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"=\n" +
	"\tDeleteReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"V\n" +
	"\n" +
	"DeleteResp\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x05R\adeleted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"X\n" +
	"\tSearchReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"A\n" +
	"\n" +
	"SearchResp\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.cognevra.v1.SearchResultR\aresults\"Y\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\">\n" +
	"\n" +
	"GetByIDReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"A\n" +
	"\vGetByIDResp\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.cognevra.v1.RecordEntryR\arecords\"p\n" +
	"\vRecordEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmetadata_json\x18\x02 \x01(\tR\fmetadataJson\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x16\n" +
	"\x06vector\x18\x04 \x03(\x02R\x06vector\"\xaf\x01\n" +
	"\fChunkTextReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12&\n" +
	"\x0fmin_chunk_chars\x18\x03 \x01(\x05R\rminChunkChars\x12&\n" +
	"\x0fmax_chunk_chars\x18\x04 \x01(\x05R\rmaxChunkChars\x12\x1f\n" +
	"\vdocument_id\x18\x05 \x01(\tR\n" +
	"documentId\"?\n" +
	"\rChunkTextResp\x12.\n" +
	"\x06chunks\x18\x01 \x03(\v2\x16.cognevra.v1.TextChunkR\x06chunks\"\x85\x01\n" +
	"\tTextChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\achapter\x18\x03 \x01(\x05R\achapter\x12\x1f\n" +
	"\vchunk_index\x18\x04 \x01(\x05R\n" +
	"chunkIndex\x12\x19\n" +
	"\bcut_type\x18\x05 \x01(\tR\acutType\"z\n" +
	"\bInfoResp\x12\x1c\n" +
	"\tdimension\x18\x01 \x01(\x05R\tdimension\x12\x16\n" +
	"\x06shards\x18\x02 \x01(\x05R\x06shards\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\vcollections\x18\x04 \x03(\tR\vcollections\"p\n" +
	"\x12ProcessTripletsReq\x12,\n" +
	"\x05nodes\x18\x01 \x03(\v2\x16.cognevra.v1.GraphNodeR\x05nodes\x12,\n" +
	"\x05edges\x18\x02 \x03(\v2\x16.cognevra.v1.GraphEdgeR\x05edges\"/\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x8f\x01\n" +
	"\tGraphEdge\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12+\n" +
	"\x11relationship_name\x18\x03 \x01(\tR\x10relationshipName\x12\x1b\n" +
	"\tedge_text\x18\x04 \x01(\tR\bedgeText\"s\n" +
	"\rTripletResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ffrom_node_id\x18\x02 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x03 \x01(\tR\btoNodeId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\x81\x01\n" +
	"\x13ProcessTripletsResp\x126\n" +
	"\btriplets\x18\x01 \x03(\v2\x1a.cognevra.v1.TripletResultR\btriplets\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x05R\acreated\x12\x18\n" +
	"\askipped\x18\x03 \x01(\x05R\askipped\"T\n" +
	"\fHashFilesReq\x12\x1d\n" +
	"\n" +
	"file_paths\x18\x01 \x03(\tR\tfilePaths\x12%\n" +
	"\x0emax_concurrent\x18\x02 \x01(\x05R\rmaxConcurrent\"\x8f\x01\n" +
	"\bFileHash\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"@\n" +
	"\rHashFilesResp\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.cognevra.v1.FileHashR\aresults\"m\n" +
	"\x10ListDirectoryReq\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\x12\x1e\n" +
	"\n" +
	"extensions\x18\x03 \x03(\tR\n" +
	"extensions\"H\n" +
	"\x11ListDirectoryResp\x12\x1d\n" +
	"\n" +
	"file_paths\x18\x01 \x03(\tR\tfilePaths\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"X\n" +
	"\vCompactResp\x123\n" +
	"\x15collections_compacted\x18\x01 \x01(\x05R\x14collectionsCompacted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"X\n" +
	"\x12AggregateSearchReq\x12-\n" +
	"\x05edges\x18\x01 \x03(\v2\x17.cognevra.v1.ScoredEdgeR\x05edges\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"\xee\x02\n" +
	"\n" +
	"ScoredEdge\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x12\x1f\n" +
	"\vsource_text\x18\x03 \x01(\tR\n" +
	"sourceText\x12'\n" +
	"\x0fsource_distance\x18\x04 \x01(\x02R\x0esourceDistance\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_name\x18\x06 \x01(\tR\n" +
	"targetName\x12\x1f\n" +
	"\vtarget_text\x18\a \x01(\tR\n" +
	"targetText\x12'\n" +
	"\x0ftarget_distance\x18\b \x01(\x02R\x0etargetDistance\x12+\n" +
	"\x11relationship_name\x18\t \x01(\tR\x10relationshipName\x12#\n" +
	"\redge_distance\x18\n" +
	" \x01(\x02R\fedgeDistance\"\xa1\x01\n" +
	"\x13AggregateSearchResp\x12:\n" +
	"\franked_edges\x18\x01 \x03(\v2\x17.cognevra.v1.RankedEdgeR\vrankedEdges\x12+\n" +
	"\x11formatted_context\x18\x02 \x01(\tR\x10formattedContext\x12!\n" +
	"\funique_nodes\x18\x03 \x01(\x05R\vuniqueNodes\"\xcb\x01\n" +
	"\n" +
	"RankedEdge\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_name\x18\x04 \x01(\tR\n" +
	"targetName\x12+\n" +
	"\x11relationship_name\x18\x05 \x01(\tR\x10relationshipName\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x02R\x05score2\xed\b\n" +
	"\x0fCognevraService\x12M\n" +
	"\x10CreateCollection\x12 .cognevra.v1.CreateCollectionReq\x1a\x17.cognevra.v1.StatusResp\x12I\n" +
	"\x0eDropCollection\x12\x1e.cognevra.v1.DropCollectionReq\x1a\x17.cognevra.v1.StatusResp\x12G\n" +
	"\x0fListCollections\x12\x12.cognevra.v1.Empty\x1a .cognevra.v1.ListCollectionsResp\x12N\n" +
	"\rHasCollection\x12\x1d.cognevra.v1.HasCollectionReq\x1a\x1e.cognevra.v1.HasCollectionResp\x129\n" +
	"\x06Insert\x12\x16.cognevra.v1.InsertReq\x1a\x17.cognevra.v1.StatusResp\x12H\n" +
	"\vBatchInsert\x12\x1b.cognevra.v1.BatchInsertReq\x1a\x1c.cognevra.v1.BatchInsertResp\x129\n" +
	"\x06Delete\x12\x16.cognevra.v1.DeleteReq\x1a\x17.cognevra.v1.DeleteResp\x129\n" +
	"\x06Search\x12\x16.cognevra.v1.SearchReq\x1a\x17.cognevra.v1.SearchResp\x12B\n" +
	"\tChunkText\x12\x19.cognevra.v1.ChunkTextReq\x1a\x1a.cognevra.v1.ChunkTextResp\x121\n" +
	"\x04Info\x12\x12.cognevra.v1.Empty\x1a\x15.cognevra.v1.InfoResp\x12<\n" +
	"\aGetByID\x12\x17.cognevra.v1.GetByIDReq\x1a\x18.cognevra.v1.GetByIDResp\x12T\n" +
	"\x0fProcessTriplets\x12\x1f.cognevra.v1.ProcessTripletsReq\x1a .cognevra.v1.ProcessTripletsResp\x12B\n" +
	"\tHashFiles\x12\x19.cognevra.v1.HashFilesReq\x1a\x1a.cognevra.v1.HashFilesResp\x12N\n" +
	"\rListDirectory\x12\x1d.cognevra.v1.ListDirectoryReq\x1a\x1e.cognevra.v1.ListDirectoryResp\x12T\n" +
	"\x0fAggregateSearch\x12\x1f.cognevra.v1.AggregateSearchReq\x1a .cognevra.v1.AggregateSearchResp\x127\n" +
	"\aCompact\x12\x12.cognevra.v1.Empty\x1a\x18.cognevra.v1.CompactRespB(Z&github.com/rupamthxt/cognevra/proto/pbb\x06proto3"

var (
	file_proto_cognevra_proto_rawDescOnce sync.Once
	file_proto_cognevra_proto_rawDescData []byte
)

func file_proto_cognevra_proto_rawDescGZIP() []byte {
	file_proto_cognevra_proto_rawDescOnce.Do(func() {
		file_proto_cognevra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cognevra_proto_rawDesc), len(file_proto_cognevra_proto_rawDesc)))
	})
	return file_proto_cognevra_proto_rawDescData
}

var file_proto_cognevra_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_proto_cognevra_proto_goTypes = []any{
	(*Empty)(nil),               // 0: cognevra.v1.Empty
	(*StatusResp)(nil),          // 1: cognevra.v1.StatusResp
	(*CreateCollectionReq)(nil), // 2: cognevra.v1.CreateCollectionReq
	(*DropCollectionReq)(nil),   // 3: cognevra.v1.DropCollectionReq
	(*ListCollectionsResp)(nil), // 4: cognevra.v1.ListCollectionsResp
	(*HasCollectionReq)(nil),    // 5: cognevra.v1.HasCollectionReq
	(*HasCollectionResp)(nil),   // 6: cognevra.v1.HasCollectionResp
	(*InsertReq)(nil),           // 7: cognevra.v1.InsertReq
	(*BatchInsertReq)(nil),      // 8: cognevra.v1.BatchInsertReq
	(*InsertRecord)(nil),        // 9: cognevra.v1.InsertRecord
	(*BatchInsertResp)(nil),     // 10: cognevra.v1.BatchInsertResp
	(*DeleteReq)(nil),           // 11: cognevra.v1.DeleteReq
	(*DeleteResp)(nil),          // 12: cognevra.v1.DeleteResp
	(*SearchReq)(nil),           // 13: cognevra.v1.SearchReq
	(*SearchResp)(nil),          // 14: cognevra.v1.SearchResp
	(*SearchResult)(nil),        // 15: cognevra.v1.SearchResult
	(*GetByIDReq)(nil),          // 16: cognevra.v1.GetByIDReq
	(*GetByIDResp)(nil),         // 17: cognevra.v1.GetByIDResp
	(*RecordEntry)(nil),         // 18: cognevra.v1.RecordEntry
	(*ChunkTextReq)(nil),        // 19: cognevra.v1.ChunkTextReq
	(*ChunkTextResp)(nil),       // 20: cognevra.v1.ChunkTextResp
	(*TextChunk)(nil),           // 21: cognevra.v1.TextChunk
	(*InfoResp)(nil),            // 22: cognevra.v1.InfoResp
	(*ProcessTripletsReq)(nil),  // 23: cognevra.v1.ProcessTripletsReq
	(*GraphNode)(nil),           // 24: cognevra.v1.GraphNode
	(*GraphEdge)(nil),           // 25: cognevra.v1.GraphEdge
	(*TripletResult)(nil),       // 26: cognevra.v1.TripletResult
	(*ProcessTripletsResp)(nil), // 27: cognevra.v1.ProcessTripletsResp
	(*HashFilesReq)(nil),        // 28: cognevra.v1.HashFilesReq
	(*FileHash)(nil),            // 29: cognevra.v1.FileHash
	(*HashFilesResp)(nil),       // 30: cognevra.v1.HashFilesResp
	(*ListDirectoryReq)(nil),    // 31: cognevra.v1.ListDirectoryReq
	(*ListDirectoryResp)(nil),   // 32: cognevra.v1.ListDirectoryResp
	(*CompactResp)(nil),         // 33: cognevra.v1.CompactResp
	(*AggregateSearchReq)(nil),  // 34: cognevra.v1.AggregateSearchReq
	(*ScoredEdge)(nil),          // 35: cognevra.v1.ScoredEdge
	(*AggregateSearchResp)(nil), // 36: cognevra.v1.AggregateSearchResp
	(*RankedEdge)(nil),          // 37: cognevra.v1.RankedEdge
}
var file_proto_cognevra_proto_depIdxs = []int32{
	9,  // 0: cognevra.v1.BatchInsertReq.records:type_name -> cognevra.v1.InsertRecord
	15, // 1: cognevra.v1.SearchResp.results:type_name -> cognevra.v1.SearchResult
	18, // 2: cognevra.v1.GetByIDResp.records:type_name -> cognevra.v1.RecordEntry
	21, // 3: cognevra.v1.ChunkTextResp.chunks:type_name -> cognevra.v1.TextChunk
	24, // 4: cognevra.v1.ProcessTripletsReq.nodes:type_name -> cognevra.v1.GraphNode
	25, // 5: cognevra.v1.ProcessTripletsReq.edges:type_name -> cognevra.v1.GraphEdge
	26, // 6: cognevra.v1.ProcessTripletsResp.triplets:type_name -> cognevra.v1.TripletResult
	29, // 7: cognevra.v1.HashFilesResp.results:type_name -> cognevra.v1.FileHash
	35, // 8: cognevra.v1.AggregateSearchReq.edges:type_name -> cognevra.v1.ScoredEdge
	37, // 9: cognevra.v1.AggregateSearchResp.ranked_edges:type_name -> cognevra.v1.RankedEdge
	2,  // 10: cognevra.v1.CognevraService.CreateCollection:input_type -> cognevra.v1.CreateCollectionReq
	3,  // 11: cognevra.v1.CognevraService.DropCollection:input_type -> cognevra.v1.DropCollectionReq
	0,  // 12: cognevra.v1.CognevraService.ListCollections:input_type -> cognevra.v1.Empty
	5,  // 13: cognevra.v1.CognevraService.HasCollection:input_type -> cognevra.v1.HasCollectionReq
	7,  // 14: cognevra.v1.CognevraService.Insert:input_type -> cognevra.v1.InsertReq
	8,  // 15: cognevra.v1.CognevraService.BatchInsert:input_type -> cognevra.v1.BatchInsertReq
	11, // 16: cognevra.v1.CognevraService.Delete:input_type -> cognevra.v1.DeleteReq
	13, // 17: cognevra.v1.CognevraService.Search:input_type -> cognevra.v1.SearchReq
	19, // 18: cognevra.v1.CognevraService.ChunkText:input_type -> cognevra.v1.ChunkTextReq
	0,  // 19: cognevra.v1.CognevraService.Info:input_type -> cognevra.v1.Empty
	16, // 20: cognevra.v1.CognevraService.GetByID:input_type -> cognevra.v1.GetByIDReq
	23, // 21: cognevra.v1.CognevraService.ProcessTriplets:input_type -> cognevra.v1.ProcessTripletsReq
	28, // 22: cognevra.v1.CognevraService.HashFiles:input_type -> cognevra.v1.HashFilesReq
	31, // 23: cognevra.v1.CognevraService.ListDirectory:input_type -> cognevra.v1.ListDirectoryReq
	34, // 24: cognevra.v1.CognevraService.AggregateSearch:input_type -> cognevra.v1.AggregateSearchReq
	0,  // 25: cognevra.v1.CognevraService.Compact:input_type -> cognevra.v1.Empty
	1,  // 26: cognevra.v1.CognevraService.CreateCollection:output_type -> cognevra.v1.StatusResp
	1,  // 27: cognevra.v1.CognevraService.DropCollection:output_type -> cognevra.v1.StatusResp
	4,  // 28: cognevra.v1.CognevraService.ListCollections:output_type -> cognevra.v1.ListCollectionsResp
	6,  // 29: cognevra.v1.CognevraService.HasCollection:output_type -> cognevra.v1.HasCollectionResp
	1,  // 30: cognevra.v1.CognevraService.Insert:output_type -> cognevra.v1.StatusResp
	10, // 31: cognevra.v1.CognevraService.BatchInsert:output_type -> cognevra.v1.BatchInsertResp
	12, // 32: cognevra.v1.CognevraService.Delete:output_type -> cognevra.v1.DeleteResp
	14, // 33: cognevra.v1.CognevraService.Search:output_type -> cognevra.v1.SearchResp
	20, // 34: cognevra.v1.CognevraService.ChunkText:output_type -> cognevra.v1.ChunkTextResp
	22, // 35: cognevra.v1.CognevraService.Info:output_type -> cognevra.v1.InfoResp
	17, // 36: cognevra.v1.CognevraService.GetByID:output_type -> cognevra.v1.GetByIDResp
	27, // 37: cognevra.v1.CognevraService.ProcessTriplets:output_type -> cognevra.v1.ProcessTripletsResp
	30, // 38: cognevra.v1.CognevraService.HashFiles:output_type -> cognevra.v1.HashFilesResp
	32, // 39: cognevra.v1.CognevraService.ListDirectory:output_type -> cognevra.v1.ListDirectoryResp
	36, // 40: cognevra.v1.CognevraService.AggregateSearch:output_type -> cognevra.v1.AggregateSearchResp
	33, // 41: cognevra.v1.CognevraService.Compact:output_type -> cognevra.v1.CompactResp
	26, // [26:42] is the sub-list for method output_type
	10, // [10:26] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_cognevra_proto_init() }
func file_proto_cognevra_proto_init() {
	if File_proto_cognevra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cognevra_proto_rawDesc), len(file_proto_cognevra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cognevra_proto_goTypes,
		DependencyIndexes: file_proto_cognevra_proto_depIdxs,
		MessageInfos:      file_proto_cognevra_proto_msgTypes,
	}.Build()
	File_proto_cognevra_proto = out.File
	file_proto_cognevra_proto_goTypes = nil
	file_proto_cognevra_proto_depIdxs = nil
}
