// levara_v2.proto — next-generation Levara gRPC API (T10).
//
// Design goals:
//   1. Fix the naming drift that made v1 confusing (Insert vs Add vs Save
//      vs Create). v2 keeps Insert as the canonical write and exposes
//      Add/Save/Create as `deprecated=true` aliases so clients can migrate
//      one RPC at a time — per 20.04-tasks.md D12.
//   2. Introduce a typed ErrorDetail so clients can distinguish validation
//      errors from auth errors from backend errors without parsing the
//      status message string.
//   3. Reserve field numbers in every message so renaming a field later
//      doesn't accidentally reuse a wire tag that older clients still know.
//
// v1 stays active for 3 months post-v2-launch (D11). Both services are
// registered on the same port; a v2-aware client picks its flavour via
// the service name, a v1 client sees v2 as not-implemented.
//
// This file is authored but NOT yet code-generated in this commit. Run
// `make proto` once protoc-gen-go is wired into CI; in the meantime the
// file serves as the reviewable contract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: levara_v2.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Error model ────────────────────────────────────────────────────
//
// Every v2 response that can fail carries an optional ErrorDetail in
// addition to the gRPC status code. Clients inspect Code to branch on
// categories; Details carries key/value pairs specific to each category
// (e.g. field="vector" for validation, retry_after="60" for rate-limit).
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_levara_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type InsertReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertReq) Reset() {
	*x = InsertReq{}
	mi := &file_levara_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertReq) ProtoMessage() {}

func (x *InsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertReq.ProtoReflect.Descriptor instead.
func (*InsertReq) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{1}
}

func (x *InsertReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertReq) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type InsertResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResp) Reset() {
	*x = InsertResp{}
	mi := &file_levara_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResp) ProtoMessage() {}

func (x *InsertResp) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResp.ProtoReflect.Descriptor instead.
func (*InsertResp) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{2}
}

func (x *InsertResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InsertResp) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type BatchInsertReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Items         []*InsertItem          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertReq) Reset() {
	*x = BatchInsertReq{}
	mi := &file_levara_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertReq) ProtoMessage() {}

func (x *BatchInsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertReq.ProtoReflect.Descriptor instead.
func (*BatchInsertReq) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{3}
}

func (x *BatchInsertReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BatchInsertReq) GetItems() []*InsertItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type InsertItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertItem) Reset() {
	*x = InsertItem{}
	mi := &file_levara_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertItem) ProtoMessage() {}

func (x *InsertItem) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertItem.ProtoReflect.Descriptor instead.
func (*InsertItem) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{4}
}

func (x *InsertItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertItem) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertItem) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type BatchInsertResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Failures      []*BatchInsertFailure  `protobuf:"bytes,3,rep,name=failures,proto3" json:"failures,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertResp) Reset() {
	*x = BatchInsertResp{}
	mi := &file_levara_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertResp) ProtoMessage() {}

func (x *BatchInsertResp) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertResp.ProtoReflect.Descriptor instead.
func (*BatchInsertResp) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{5}
}

func (x *BatchInsertResp) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *BatchInsertResp) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchInsertResp) GetFailures() []*BatchInsertFailure {
	if x != nil {
		return x.Failures
	}
	return nil
}

func (x *BatchInsertResp) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type BatchInsertFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertFailure) Reset() {
	*x = BatchInsertFailure{}
	mi := &file_levara_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertFailure) ProtoMessage() {}

func (x *BatchInsertFailure) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertFailure.ProtoReflect.Descriptor instead.
func (*BatchInsertFailure) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{6}
}

func (x *BatchInsertFailure) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BatchInsertFailure) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_levara_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int32                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_levara_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResp) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteResp) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *DeleteResp) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_levara_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{9}
}

func (x *SearchReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_levara_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResp) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResp) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_levara_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{11}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type InfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoReq) Reset() {
	*x = InfoReq{}
	mi := &file_levara_v2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReq) ProtoMessage() {}

func (x *InfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReq.ProtoReflect.Descriptor instead.
func (*InfoReq) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{12}
}

type InfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimension     int32                  `protobuf:"varint,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Shards        int32                  `protobuf:"varint,2,opt,name=shards,proto3" json:"shards,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResp) Reset() {
	*x = InfoResp{}
	mi := &file_levara_v2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResp) ProtoMessage() {}

func (x *InfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_levara_v2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResp.ProtoReflect.Descriptor instead.
func (*InfoResp) Descriptor() ([]byte, []int) {
	return file_levara_v2_proto_rawDescGZIP(), []int{13}
}

func (x *InfoResp) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *InfoResp) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *InfoResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_levara_v2_proto protoreflect.FileDescriptor

const file_levara_v2_proto_rawDesc = "" +
	"\n" +
	"\x0flevara_v2.proto\x12\tlevara.v2\"\xb6\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\adetails\x18\x03 \x03(\v2#.levara.v2.ErrorDetail.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\tInsertReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\fR\fmetadataJsonJ\x04\b2\x10e\"P\n" +
	"\n" +
	"InsertResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x16.levara.v2.ErrorDetailR\x05errorJ\x04\b2\x10e\"c\n" +
	"\x0eBatchInsertReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.levara.v2.InsertItemR\x05itemsJ\x04\b2\x10e\"_\n" +
	"\n" +
	"InsertItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJsonJ\x04\b2\x10e\"\xb4\x01\n" +
	"\x0fBatchInsertResp\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x129\n" +
	"\bfailures\x18\x03 \x03(\v2\x1d.levara.v2.BatchInsertFailureR\bfailures\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x16.levara.v2.ErrorDetailR\x05errorJ\x04\b2\x10e\"X\n" +
	"\x12BatchInsertFailure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x16.levara.v2.ErrorDetailR\x05errorJ\x04\b2\x10e\"C\n" +
	"\tDeleteReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03idsJ\x04\b2\x10e\"r\n" +
	"\n" +
	"DeleteResp\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x05R\adeleted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x16.levara.v2.ErrorDetailR\x05errorJ\x04\b2\x10e\"^\n" +
	"\tSearchReq\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topKJ\x04\b2\x10e\"s\n" +
	"\n" +
	"SearchResp\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.levara.v2.SearchResultR\aresults\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x16.levara.v2.ErrorDetailR\x05errorJ\x04\b2\x10e\"_\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJsonJ\x04\b2\x10e\"\t\n" +
	"\aInfoReq\"`\n" +
	"\bInfoResp\x12\x1c\n" +
	"\tdimension\x18\x01 \x01(\x05R\tdimension\x12\x16\n" +
	"\x06shards\x18\x02 \x01(\x05R\x06shards\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversionJ\x04\b2\x10e2\xdc\x03\n" +
	"\x0fLevaraServiceV2\x125\n" +
	"\x06Insert\x12\x14.levara.v2.InsertReq\x1a\x15.levara.v2.InsertResp\x127\n" +
	"\x03Add\x12\x14.levara.v2.InsertReq\x1a\x15.levara.v2.InsertResp\"\x03\x88\x02\x01\x128\n" +
	"\x04Save\x12\x14.levara.v2.InsertReq\x1a\x15.levara.v2.InsertResp\"\x03\x88\x02\x01\x12:\n" +
	"\x06Create\x12\x14.levara.v2.InsertReq\x1a\x15.levara.v2.InsertResp\"\x03\x88\x02\x01\x12D\n" +
	"\vBatchInsert\x12\x19.levara.v2.BatchInsertReq\x1a\x1a.levara.v2.BatchInsertResp\x125\n" +
	"\x06Delete\x12\x14.levara.v2.DeleteReq\x1a\x15.levara.v2.DeleteResp\x125\n" +
	"\x06Search\x12\x14.levara.v2.SearchReq\x1a\x15.levara.v2.SearchResp\x12/\n" +
	"\x04Info\x12\x12.levara.v2.InfoReq\x1a\x13.levara.v2.InfoRespB&Z$github.com/stek0v/levara/proto/pb/v2b\x06proto3"

var (
	file_levara_v2_proto_rawDescOnce sync.Once
	file_levara_v2_proto_rawDescData []byte
)

func file_levara_v2_proto_rawDescGZIP() []byte {
	file_levara_v2_proto_rawDescOnce.Do(func() {
		file_levara_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_levara_v2_proto_rawDesc), len(file_levara_v2_proto_rawDesc)))
	})
	return file_levara_v2_proto_rawDescData
}

var file_levara_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_levara_v2_proto_goTypes = []any{
	(*ErrorDetail)(nil),        // 0: levara.v2.ErrorDetail
	(*InsertReq)(nil),          // 1: levara.v2.InsertReq
	(*InsertResp)(nil),         // 2: levara.v2.InsertResp
	(*BatchInsertReq)(nil),     // 3: levara.v2.BatchInsertReq
	(*InsertItem)(nil),         // 4: levara.v2.InsertItem
	(*BatchInsertResp)(nil),    // 5: levara.v2.BatchInsertResp
	(*BatchInsertFailure)(nil), // 6: levara.v2.BatchInsertFailure
	(*DeleteReq)(nil),          // 7: levara.v2.DeleteReq
	(*DeleteResp)(nil),         // 8: levara.v2.DeleteResp
	(*SearchReq)(nil),          // 9: levara.v2.SearchReq
	(*SearchResp)(nil),         // 10: levara.v2.SearchResp
	(*SearchResult)(nil),       // 11: levara.v2.SearchResult
	(*InfoReq)(nil),            // 12: levara.v2.InfoReq
	(*InfoResp)(nil),           // 13: levara.v2.InfoResp
	nil,                        // 14: levara.v2.ErrorDetail.DetailsEntry
}
var file_levara_v2_proto_depIdxs = []int32{
	14, // 0: levara.v2.ErrorDetail.details:type_name -> levara.v2.ErrorDetail.DetailsEntry
	0,  // 1: levara.v2.InsertResp.error:type_name -> levara.v2.ErrorDetail
	4,  // 2: levara.v2.BatchInsertReq.items:type_name -> levara.v2.InsertItem
	6,  // 3: levara.v2.BatchInsertResp.failures:type_name -> levara.v2.BatchInsertFailure
	0,  // 4: levara.v2.BatchInsertResp.error:type_name -> levara.v2.ErrorDetail
	0,  // 5: levara.v2.BatchInsertFailure.error:type_name -> levara.v2.ErrorDetail
	0,  // 6: levara.v2.DeleteResp.error:type_name -> levara.v2.ErrorDetail
	11, // 7: levara.v2.SearchResp.results:type_name -> levara.v2.SearchResult
	0,  // 8: levara.v2.SearchResp.error:type_name -> levara.v2.ErrorDetail
	1,  // 9: levara.v2.LevaraServiceV2.Insert:input_type -> levara.v2.InsertReq
	1,  // 10: levara.v2.LevaraServiceV2.Add:input_type -> levara.v2.InsertReq
	1,  // 11: levara.v2.LevaraServiceV2.Save:input_type -> levara.v2.InsertReq
	1,  // 12: levara.v2.LevaraServiceV2.Create:input_type -> levara.v2.InsertReq
	3,  // 13: levara.v2.LevaraServiceV2.BatchInsert:input_type -> levara.v2.BatchInsertReq
	7,  // 14: levara.v2.LevaraServiceV2.Delete:input_type -> levara.v2.DeleteReq
	9,  // 15: levara.v2.LevaraServiceV2.Search:input_type -> levara.v2.SearchReq
	12, // 16: levara.v2.LevaraServiceV2.Info:input_type -> levara.v2.InfoReq
	2,  // 17: levara.v2.LevaraServiceV2.Insert:output_type -> levara.v2.InsertResp
	2,  // 18: levara.v2.LevaraServiceV2.Add:output_type -> levara.v2.InsertResp
	2,  // 19: levara.v2.LevaraServiceV2.Save:output_type -> levara.v2.InsertResp
	2,  // 20: levara.v2.LevaraServiceV2.Create:output_type -> levara.v2.InsertResp
	5,  // 21: levara.v2.LevaraServiceV2.BatchInsert:output_type -> levara.v2.BatchInsertResp
	8,  // 22: levara.v2.LevaraServiceV2.Delete:output_type -> levara.v2.DeleteResp
	10, // 23: levara.v2.LevaraServiceV2.Search:output_type -> levara.v2.SearchResp
	13, // 24: levara.v2.LevaraServiceV2.Info:output_type -> levara.v2.InfoResp
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_levara_v2_proto_init() }
func file_levara_v2_proto_init() {
	if File_levara_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_levara_v2_proto_rawDesc), len(file_levara_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_levara_v2_proto_goTypes,
		DependencyIndexes: file_levara_v2_proto_depIdxs,
		MessageInfos:      file_levara_v2_proto_msgTypes,
	}.Build()
	File_levara_v2_proto = out.File
	file_levara_v2_proto_goTypes = nil
	file_levara_v2_proto_depIdxs = nil
}
