package main

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/stek0v/levara/internal/contract"
)

func writeMarkdown(c contract.Contract, outDir string) error {
	var b strings.Builder
	fmt.Fprintf(&b, "# Levara API Contract\n\n")
	fmt.Fprintf(&b, "_Generated by `make contract`. Do not edit._\n\n")
	fmt.Fprintf(&b, "- git_rev: `%s`\n", c.GitRev)
	fmt.Fprintf(&b, "- generated_at: `%s`\n\n", c.GeneratedAt)

	fmt.Fprintf(&b, "## REST\n\n| Method | Path | Status | Group |\n|---|---|---|---|\n")
	for _, r := range c.REST {
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n", r.Method, r.Path, r.Status, r.Group)
	}

	fmt.Fprintf(&b, "\n## gRPC\n\n| Service | Method | Status |\n|---|---|---|\n")
	for _, m := range c.GRPC {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", m.Service, m.Method, m.Status)
	}

	fmt.Fprintf(&b, "\n## MCP\n\n| Tool | Group | Status |\n|---|---|---|\n")
	for _, t := range c.MCP {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", t.Name, t.Group, t.Status)
	}

	fmt.Fprintf(&b, "\n## DB Schema\n\n| Provider | Kind | Name |\n|---|---|---|\n")
	for _, s := range c.Schema {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", s.Provider, s.Kind, s.Name)
	}

	return atomicWrite(filepath.Join(outDir, "api-contract.md"), []byte(b.String()))
}
