package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/stek0v/levara/internal/contract"
)

func validate(c contract.Contract, outDir, repoRoot string) error {
	if err := compareFile(c, outDir, "contract.json", renderJSONBytes); err != nil {
		return err
	}
	if err := compareFile(c, outDir, "api-contract.md", renderMarkdownBytes); err != nil {
		return err
	}
	if err := validateDeploymentMatrix(c, repoRoot); err != nil {
		return err
	}
	return nil
}

type rendererFn func(contract.Contract) ([]byte, error)

func compareFile(c contract.Contract, outDir, name string, render rendererFn) error {
	want, err := render(c)
	if err != nil {
		return err
	}
	got, err := os.ReadFile(filepath.Join(outDir, name))
	if err != nil {
		return fmt.Errorf("%s missing — run `make contract`: %w", name, err)
	}
	if !bytes.Equal(want, got) {
		return fmt.Errorf("%s drifted — run `make contract` and commit the result", name)
	}
	return nil
}

func renderJSONBytes(c contract.Contract) ([]byte, error) {
	b, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

func renderMarkdownBytes(c contract.Contract) ([]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "# Levara API Contract\n\n")
	fmt.Fprintf(&b, "_Generated by `make contract`. Do not edit._\n\n")
	fmt.Fprintf(&b, "- git_rev: `%s`\n", c.GitRev)
	fmt.Fprintf(&b, "- generated_at: `%s`\n\n", c.GeneratedAt)
	fmt.Fprintf(&b, "## REST\n\n| Method | Path | Status | Group |\n|---|---|---|---|\n")
	for _, r := range c.REST {
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n", r.Method, r.Path, r.Status, r.Group)
	}
	fmt.Fprintf(&b, "\n## gRPC\n\n| Service | Method | Status |\n|---|---|---|\n")
	for _, m := range c.GRPC {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", m.Service, m.Method, m.Status)
	}
	fmt.Fprintf(&b, "\n## MCP\n\n| Tool | Group | Status |\n|---|---|---|\n")
	for _, t := range c.MCP {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", t.Name, t.Group, t.Status)
	}
	fmt.Fprintf(&b, "\n## DB Schema\n\n| Provider | Kind | Name |\n|---|---|---|\n")
	for _, s := range c.Schema {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", s.Provider, s.Kind, s.Name)
	}
	return []byte(b.String()), nil
}

var endpointRe = regexp.MustCompile("`(GET|POST|PUT|DELETE|PATCH|HEAD) (/[^`]+)`")

func validateDeploymentMatrix(c contract.Contract, repoRoot string) error {
	path := filepath.Join(repoRoot, "docs/deployment-matrix.md")
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	known := map[string]bool{}
	for _, r := range c.REST {
		known[r.Method+" "+r.Path] = true
	}
	for _, m := range endpointRe.FindAllStringSubmatch(string(raw), -1) {
		key := m[1] + " " + m[2]
		if !known[key] {
			return fmt.Errorf("deployment-matrix references unknown REST endpoint: %s", key)
		}
	}
	return nil
}
