// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/cognevra.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CognevraService_CreateCollection_FullMethodName        = "/cognevra.v1.CognevraService/CreateCollection"
	CognevraService_DropCollection_FullMethodName          = "/cognevra.v1.CognevraService/DropCollection"
	CognevraService_ListCollections_FullMethodName         = "/cognevra.v1.CognevraService/ListCollections"
	CognevraService_HasCollection_FullMethodName           = "/cognevra.v1.CognevraService/HasCollection"
	CognevraService_Insert_FullMethodName                  = "/cognevra.v1.CognevraService/Insert"
	CognevraService_BatchInsert_FullMethodName             = "/cognevra.v1.CognevraService/BatchInsert"
	CognevraService_Delete_FullMethodName                  = "/cognevra.v1.CognevraService/Delete"
	CognevraService_Search_FullMethodName                  = "/cognevra.v1.CognevraService/Search"
	CognevraService_ChunkText_FullMethodName               = "/cognevra.v1.CognevraService/ChunkText"
	CognevraService_Info_FullMethodName                    = "/cognevra.v1.CognevraService/Info"
	CognevraService_GetByID_FullMethodName                 = "/cognevra.v1.CognevraService/GetByID"
	CognevraService_ProcessTriplets_FullMethodName         = "/cognevra.v1.CognevraService/ProcessTriplets"
	CognevraService_HashFiles_FullMethodName               = "/cognevra.v1.CognevraService/HashFiles"
	CognevraService_ListDirectory_FullMethodName           = "/cognevra.v1.CognevraService/ListDirectory"
	CognevraService_AggregateSearch_FullMethodName         = "/cognevra.v1.CognevraService/AggregateSearch"
	CognevraService_SearchTriplets_FullMethodName          = "/cognevra.v1.CognevraService/SearchTriplets"
	CognevraService_DeduplicateGraph_FullMethodName        = "/cognevra.v1.CognevraService/DeduplicateGraph"
	CognevraService_BatchEmbedAndIndex_FullMethodName      = "/cognevra.v1.CognevraService/BatchEmbedAndIndex"
	CognevraService_BatchWriteGraph_FullMethodName         = "/cognevra.v1.CognevraService/BatchWriteGraph"
	CognevraService_ParallelWriteDataPoints_FullMethodName = "/cognevra.v1.CognevraService/ParallelWriteDataPoints"
	CognevraService_SearchByText_FullMethodName            = "/cognevra.v1.CognevraService/SearchByText"
	CognevraService_BatchSearchByText_FullMethodName       = "/cognevra.v1.CognevraService/BatchSearchByText"
	CognevraService_GraphRead_FullMethodName               = "/cognevra.v1.CognevraService/GraphRead"
	CognevraService_GraphCompletionSearch_FullMethodName   = "/cognevra.v1.CognevraService/GraphCompletionSearch"
	CognevraService_PipelineCognify_FullMethodName         = "/cognevra.v1.CognevraService/PipelineCognify"
	CognevraService_LLMCacheGet_FullMethodName             = "/cognevra.v1.CognevraService/LLMCacheGet"
	CognevraService_LLMCachePut_FullMethodName             = "/cognevra.v1.CognevraService/LLMCachePut"
	CognevraService_LLMCacheStats_FullMethodName           = "/cognevra.v1.CognevraService/LLMCacheStats"
	CognevraService_SemanticDedup_FullMethodName           = "/cognevra.v1.CognevraService/SemanticDedup"
	CognevraService_MultiQuerySearch_FullMethodName        = "/cognevra.v1.CognevraService/MultiQuerySearch"
	CognevraService_IngestData_FullMethodName              = "/cognevra.v1.CognevraService/IngestData"
	CognevraService_ExtractText_FullMethodName             = "/cognevra.v1.CognevraService/ExtractText"
	CognevraService_TemporalSearch_FullMethodName          = "/cognevra.v1.CognevraService/TemporalSearch"
	CognevraService_BM25Index_FullMethodName               = "/cognevra.v1.CognevraService/BM25Index"
	CognevraService_BM25Search_FullMethodName              = "/cognevra.v1.CognevraService/BM25Search"
	CognevraService_HybridSearch_FullMethodName            = "/cognevra.v1.CognevraService/HybridSearch"
	CognevraService_Compact_FullMethodName                 = "/cognevra.v1.CognevraService/Compact"
)

// CognevraServiceClient is the client API for CognevraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CognevraServiceClient interface {
	// Collections
	CreateCollection(ctx context.Context, in *CreateCollectionReq, opts ...grpc.CallOption) (*StatusResp, error)
	DropCollection(ctx context.Context, in *DropCollectionReq, opts ...grpc.CallOption) (*StatusResp, error)
	ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResp, error)
	HasCollection(ctx context.Context, in *HasCollectionReq, opts ...grpc.CallOption) (*HasCollectionResp, error)
	// Records
	Insert(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*StatusResp, error)
	BatchInsert(ctx context.Context, in *BatchInsertReq, opts ...grpc.CallOption) (*BatchInsertResp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	// Text processing
	ChunkText(ctx context.Context, in *ChunkTextReq, opts ...grpc.CallOption) (*ChunkTextResp, error)
	// Info
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResp, error)
	// Record retrieval
	GetByID(ctx context.Context, in *GetByIDReq, opts ...grpc.CallOption) (*GetByIDResp, error)
	// Triplet processing
	ProcessTriplets(ctx context.Context, in *ProcessTripletsReq, opts ...grpc.CallOption) (*ProcessTripletsResp, error)
	// File I/O acceleration
	HashFiles(ctx context.Context, in *HashFilesReq, opts ...grpc.CallOption) (*HashFilesResp, error)
	ListDirectory(ctx context.Context, in *ListDirectoryReq, opts ...grpc.CallOption) (*ListDirectoryResp, error)
	// Search aggregation
	AggregateSearch(ctx context.Context, in *AggregateSearchReq, opts ...grpc.CallOption) (*AggregateSearchResp, error)
	// Triplet search (in-memory graph scoring)
	SearchTriplets(ctx context.Context, in *SearchTripletsReq, opts ...grpc.CallOption) (*SearchTripletsResp, error)
	// Graph deduplication + triplet generation
	DeduplicateGraph(ctx context.Context, in *DeduplicateGraphReq, opts ...grpc.CallOption) (*DeduplicateGraphResp, error)
	// Batch embed + index (embed texts → insert vectors into collections)
	BatchEmbedAndIndex(ctx context.Context, in *BatchEmbedAndIndexReq, opts ...grpc.CallOption) (*BatchEmbedAndIndexResp, error)
	// Batch write nodes/edges to Neo4j
	BatchWriteGraph(ctx context.Context, in *BatchWriteGraphReq, opts ...grpc.CallOption) (*BatchWriteGraphResp, error)
	// Parallel write: dedup + Neo4j + embed + vector index in one call
	ParallelWriteDataPoints(ctx context.Context, in *ParallelWriteReq, opts ...grpc.CallOption) (*ParallelWriteResp, error)
	// End-to-end text search: embed query + vector search in one call (no Python roundtrip)
	SearchByText(ctx context.Context, in *SearchByTextReq, opts ...grpc.CallOption) (*SearchResp, error)
	BatchSearchByText(ctx context.Context, in *BatchSearchByTextReq, opts ...grpc.CallOption) (*BatchSearchByTextResp, error)
	// Neo4j graph read queries (search-time)
	GraphRead(ctx context.Context, in *GraphReadReq, opts ...grpc.CallOption) (*GraphReadResp, error)
	// Full graph search: embed → vector search → Neo4j graph → triplet scoring → context
	GraphCompletionSearch(ctx context.Context, in *GraphCompletionSearchReq, opts ...grpc.CallOption) (*GraphCompletionSearchResp, error)
	// Pipeline orchestrator (server-side streaming)
	PipelineCognify(ctx context.Context, in *PipelineCognifyReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PipelineCognifyProgress], error)
	// LLM response cache
	LLMCacheGet(ctx context.Context, in *LLMCacheGetReq, opts ...grpc.CallOption) (*LLMCacheGetResp, error)
	LLMCachePut(ctx context.Context, in *LLMCachePutReq, opts ...grpc.CallOption) (*StatusResp, error)
	LLMCacheStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LLMCacheStatsResp, error)
	// Semantic deduplication (vector cosine similarity)
	SemanticDedup(ctx context.Context, in *SemanticDedupReq, opts ...grpc.CallOption) (*SemanticDedupResp, error)
	// Multi-query search: decompose → parallel search → merge
	MultiQuerySearch(ctx context.Context, in *MultiQuerySearchReq, opts ...grpc.CallOption) (*MultiQuerySearchResp, error)
	// Fast data ingestion: hash + save + classify in one Go call
	IngestData(ctx context.Context, in *IngestDataReq, opts ...grpc.CallOption) (*IngestDataResp, error)
	// Text extraction from PDF/DOCX/TXT (pure Go)
	ExtractText(ctx context.Context, in *ExtractTextReq, opts ...grpc.CallOption) (*ExtractTextResp, error)
	// Temporal search: extract timestamps from text + range query
	TemporalSearch(ctx context.Context, in *TemporalSearchReq, opts ...grpc.CallOption) (*TemporalSearchResp, error)
	// BM25 lexical search + hybrid
	BM25Index(ctx context.Context, in *BM25IndexReq, opts ...grpc.CallOption) (*StatusResp, error)
	BM25Search(ctx context.Context, in *BM25SearchReq, opts ...grpc.CallOption) (*BM25SearchResp, error)
	HybridSearch(ctx context.Context, in *HybridSearchReq, opts ...grpc.CallOption) (*HybridSearchResp, error)
	// Maintenance
	Compact(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CompactResp, error)
}

type cognevraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCognevraServiceClient(cc grpc.ClientConnInterface) CognevraServiceClient {
	return &cognevraServiceClient{cc}
}

func (c *cognevraServiceClient) CreateCollection(ctx context.Context, in *CreateCollectionReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, CognevraService_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) DropCollection(ctx context.Context, in *DropCollectionReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, CognevraService_DropCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResp)
	err := c.cc.Invoke(ctx, CognevraService_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) HasCollection(ctx context.Context, in *HasCollectionReq, opts ...grpc.CallOption) (*HasCollectionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasCollectionResp)
	err := c.cc.Invoke(ctx, CognevraService_HasCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) Insert(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, CognevraService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) BatchInsert(ctx context.Context, in *BatchInsertReq, opts ...grpc.CallOption) (*BatchInsertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInsertResp)
	err := c.cc.Invoke(ctx, CognevraService_BatchInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, CognevraService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, CognevraService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) ChunkText(ctx context.Context, in *ChunkTextReq, opts ...grpc.CallOption) (*ChunkTextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkTextResp)
	err := c.cc.Invoke(ctx, CognevraService_ChunkText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResp)
	err := c.cc.Invoke(ctx, CognevraService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) GetByID(ctx context.Context, in *GetByIDReq, opts ...grpc.CallOption) (*GetByIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByIDResp)
	err := c.cc.Invoke(ctx, CognevraService_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) ProcessTriplets(ctx context.Context, in *ProcessTripletsReq, opts ...grpc.CallOption) (*ProcessTripletsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessTripletsResp)
	err := c.cc.Invoke(ctx, CognevraService_ProcessTriplets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) HashFiles(ctx context.Context, in *HashFilesReq, opts ...grpc.CallOption) (*HashFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashFilesResp)
	err := c.cc.Invoke(ctx, CognevraService_HashFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) ListDirectory(ctx context.Context, in *ListDirectoryReq, opts ...grpc.CallOption) (*ListDirectoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirectoryResp)
	err := c.cc.Invoke(ctx, CognevraService_ListDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) AggregateSearch(ctx context.Context, in *AggregateSearchReq, opts ...grpc.CallOption) (*AggregateSearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregateSearchResp)
	err := c.cc.Invoke(ctx, CognevraService_AggregateSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) SearchTriplets(ctx context.Context, in *SearchTripletsReq, opts ...grpc.CallOption) (*SearchTripletsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTripletsResp)
	err := c.cc.Invoke(ctx, CognevraService_SearchTriplets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) DeduplicateGraph(ctx context.Context, in *DeduplicateGraphReq, opts ...grpc.CallOption) (*DeduplicateGraphResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeduplicateGraphResp)
	err := c.cc.Invoke(ctx, CognevraService_DeduplicateGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) BatchEmbedAndIndex(ctx context.Context, in *BatchEmbedAndIndexReq, opts ...grpc.CallOption) (*BatchEmbedAndIndexResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchEmbedAndIndexResp)
	err := c.cc.Invoke(ctx, CognevraService_BatchEmbedAndIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) BatchWriteGraph(ctx context.Context, in *BatchWriteGraphReq, opts ...grpc.CallOption) (*BatchWriteGraphResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchWriteGraphResp)
	err := c.cc.Invoke(ctx, CognevraService_BatchWriteGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) ParallelWriteDataPoints(ctx context.Context, in *ParallelWriteReq, opts ...grpc.CallOption) (*ParallelWriteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParallelWriteResp)
	err := c.cc.Invoke(ctx, CognevraService_ParallelWriteDataPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) SearchByText(ctx context.Context, in *SearchByTextReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, CognevraService_SearchByText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) BatchSearchByText(ctx context.Context, in *BatchSearchByTextReq, opts ...grpc.CallOption) (*BatchSearchByTextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSearchByTextResp)
	err := c.cc.Invoke(ctx, CognevraService_BatchSearchByText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) GraphRead(ctx context.Context, in *GraphReadReq, opts ...grpc.CallOption) (*GraphReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphReadResp)
	err := c.cc.Invoke(ctx, CognevraService_GraphRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) GraphCompletionSearch(ctx context.Context, in *GraphCompletionSearchReq, opts ...grpc.CallOption) (*GraphCompletionSearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphCompletionSearchResp)
	err := c.cc.Invoke(ctx, CognevraService_GraphCompletionSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) PipelineCognify(ctx context.Context, in *PipelineCognifyReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PipelineCognifyProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CognevraService_ServiceDesc.Streams[0], CognevraService_PipelineCognify_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PipelineCognifyReq, PipelineCognifyProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognevraService_PipelineCognifyClient = grpc.ServerStreamingClient[PipelineCognifyProgress]

func (c *cognevraServiceClient) LLMCacheGet(ctx context.Context, in *LLMCacheGetReq, opts ...grpc.CallOption) (*LLMCacheGetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLMCacheGetResp)
	err := c.cc.Invoke(ctx, CognevraService_LLMCacheGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) LLMCachePut(ctx context.Context, in *LLMCachePutReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, CognevraService_LLMCachePut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) LLMCacheStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LLMCacheStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLMCacheStatsResp)
	err := c.cc.Invoke(ctx, CognevraService_LLMCacheStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) SemanticDedup(ctx context.Context, in *SemanticDedupReq, opts ...grpc.CallOption) (*SemanticDedupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SemanticDedupResp)
	err := c.cc.Invoke(ctx, CognevraService_SemanticDedup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) MultiQuerySearch(ctx context.Context, in *MultiQuerySearchReq, opts ...grpc.CallOption) (*MultiQuerySearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiQuerySearchResp)
	err := c.cc.Invoke(ctx, CognevraService_MultiQuerySearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) IngestData(ctx context.Context, in *IngestDataReq, opts ...grpc.CallOption) (*IngestDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestDataResp)
	err := c.cc.Invoke(ctx, CognevraService_IngestData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) ExtractText(ctx context.Context, in *ExtractTextReq, opts ...grpc.CallOption) (*ExtractTextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractTextResp)
	err := c.cc.Invoke(ctx, CognevraService_ExtractText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) TemporalSearch(ctx context.Context, in *TemporalSearchReq, opts ...grpc.CallOption) (*TemporalSearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemporalSearchResp)
	err := c.cc.Invoke(ctx, CognevraService_TemporalSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) BM25Index(ctx context.Context, in *BM25IndexReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, CognevraService_BM25Index_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) BM25Search(ctx context.Context, in *BM25SearchReq, opts ...grpc.CallOption) (*BM25SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BM25SearchResp)
	err := c.cc.Invoke(ctx, CognevraService_BM25Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) HybridSearch(ctx context.Context, in *HybridSearchReq, opts ...grpc.CallOption) (*HybridSearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HybridSearchResp)
	err := c.cc.Invoke(ctx, CognevraService_HybridSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognevraServiceClient) Compact(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CompactResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactResp)
	err := c.cc.Invoke(ctx, CognevraService_Compact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CognevraServiceServer is the server API for CognevraService service.
// All implementations must embed UnimplementedCognevraServiceServer
// for forward compatibility.
type CognevraServiceServer interface {
	// Collections
	CreateCollection(context.Context, *CreateCollectionReq) (*StatusResp, error)
	DropCollection(context.Context, *DropCollectionReq) (*StatusResp, error)
	ListCollections(context.Context, *Empty) (*ListCollectionsResp, error)
	HasCollection(context.Context, *HasCollectionReq) (*HasCollectionResp, error)
	// Records
	Insert(context.Context, *InsertReq) (*StatusResp, error)
	BatchInsert(context.Context, *BatchInsertReq) (*BatchInsertResp, error)
	Delete(context.Context, *DeleteReq) (*DeleteResp, error)
	Search(context.Context, *SearchReq) (*SearchResp, error)
	// Text processing
	ChunkText(context.Context, *ChunkTextReq) (*ChunkTextResp, error)
	// Info
	Info(context.Context, *Empty) (*InfoResp, error)
	// Record retrieval
	GetByID(context.Context, *GetByIDReq) (*GetByIDResp, error)
	// Triplet processing
	ProcessTriplets(context.Context, *ProcessTripletsReq) (*ProcessTripletsResp, error)
	// File I/O acceleration
	HashFiles(context.Context, *HashFilesReq) (*HashFilesResp, error)
	ListDirectory(context.Context, *ListDirectoryReq) (*ListDirectoryResp, error)
	// Search aggregation
	AggregateSearch(context.Context, *AggregateSearchReq) (*AggregateSearchResp, error)
	// Triplet search (in-memory graph scoring)
	SearchTriplets(context.Context, *SearchTripletsReq) (*SearchTripletsResp, error)
	// Graph deduplication + triplet generation
	DeduplicateGraph(context.Context, *DeduplicateGraphReq) (*DeduplicateGraphResp, error)
	// Batch embed + index (embed texts → insert vectors into collections)
	BatchEmbedAndIndex(context.Context, *BatchEmbedAndIndexReq) (*BatchEmbedAndIndexResp, error)
	// Batch write nodes/edges to Neo4j
	BatchWriteGraph(context.Context, *BatchWriteGraphReq) (*BatchWriteGraphResp, error)
	// Parallel write: dedup + Neo4j + embed + vector index in one call
	ParallelWriteDataPoints(context.Context, *ParallelWriteReq) (*ParallelWriteResp, error)
	// End-to-end text search: embed query + vector search in one call (no Python roundtrip)
	SearchByText(context.Context, *SearchByTextReq) (*SearchResp, error)
	BatchSearchByText(context.Context, *BatchSearchByTextReq) (*BatchSearchByTextResp, error)
	// Neo4j graph read queries (search-time)
	GraphRead(context.Context, *GraphReadReq) (*GraphReadResp, error)
	// Full graph search: embed → vector search → Neo4j graph → triplet scoring → context
	GraphCompletionSearch(context.Context, *GraphCompletionSearchReq) (*GraphCompletionSearchResp, error)
	// Pipeline orchestrator (server-side streaming)
	PipelineCognify(*PipelineCognifyReq, grpc.ServerStreamingServer[PipelineCognifyProgress]) error
	// LLM response cache
	LLMCacheGet(context.Context, *LLMCacheGetReq) (*LLMCacheGetResp, error)
	LLMCachePut(context.Context, *LLMCachePutReq) (*StatusResp, error)
	LLMCacheStats(context.Context, *Empty) (*LLMCacheStatsResp, error)
	// Semantic deduplication (vector cosine similarity)
	SemanticDedup(context.Context, *SemanticDedupReq) (*SemanticDedupResp, error)
	// Multi-query search: decompose → parallel search → merge
	MultiQuerySearch(context.Context, *MultiQuerySearchReq) (*MultiQuerySearchResp, error)
	// Fast data ingestion: hash + save + classify in one Go call
	IngestData(context.Context, *IngestDataReq) (*IngestDataResp, error)
	// Text extraction from PDF/DOCX/TXT (pure Go)
	ExtractText(context.Context, *ExtractTextReq) (*ExtractTextResp, error)
	// Temporal search: extract timestamps from text + range query
	TemporalSearch(context.Context, *TemporalSearchReq) (*TemporalSearchResp, error)
	// BM25 lexical search + hybrid
	BM25Index(context.Context, *BM25IndexReq) (*StatusResp, error)
	BM25Search(context.Context, *BM25SearchReq) (*BM25SearchResp, error)
	HybridSearch(context.Context, *HybridSearchReq) (*HybridSearchResp, error)
	// Maintenance
	Compact(context.Context, *Empty) (*CompactResp, error)
	mustEmbedUnimplementedCognevraServiceServer()
}

// UnimplementedCognevraServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCognevraServiceServer struct{}

func (UnimplementedCognevraServiceServer) CreateCollection(context.Context, *CreateCollectionReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedCognevraServiceServer) DropCollection(context.Context, *DropCollectionReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DropCollection not implemented")
}
func (UnimplementedCognevraServiceServer) ListCollections(context.Context, *Empty) (*ListCollectionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedCognevraServiceServer) HasCollection(context.Context, *HasCollectionReq) (*HasCollectionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HasCollection not implemented")
}
func (UnimplementedCognevraServiceServer) Insert(context.Context, *InsertReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedCognevraServiceServer) BatchInsert(context.Context, *BatchInsertReq) (*BatchInsertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInsert not implemented")
}
func (UnimplementedCognevraServiceServer) Delete(context.Context, *DeleteReq) (*DeleteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCognevraServiceServer) Search(context.Context, *SearchReq) (*SearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedCognevraServiceServer) ChunkText(context.Context, *ChunkTextReq) (*ChunkTextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkText not implemented")
}
func (UnimplementedCognevraServiceServer) Info(context.Context, *Empty) (*InfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedCognevraServiceServer) GetByID(context.Context, *GetByIDReq) (*GetByIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedCognevraServiceServer) ProcessTriplets(context.Context, *ProcessTripletsReq) (*ProcessTripletsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessTriplets not implemented")
}
func (UnimplementedCognevraServiceServer) HashFiles(context.Context, *HashFilesReq) (*HashFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HashFiles not implemented")
}
func (UnimplementedCognevraServiceServer) ListDirectory(context.Context, *ListDirectoryReq) (*ListDirectoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDirectory not implemented")
}
func (UnimplementedCognevraServiceServer) AggregateSearch(context.Context, *AggregateSearchReq) (*AggregateSearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AggregateSearch not implemented")
}
func (UnimplementedCognevraServiceServer) SearchTriplets(context.Context, *SearchTripletsReq) (*SearchTripletsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTriplets not implemented")
}
func (UnimplementedCognevraServiceServer) DeduplicateGraph(context.Context, *DeduplicateGraphReq) (*DeduplicateGraphResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeduplicateGraph not implemented")
}
func (UnimplementedCognevraServiceServer) BatchEmbedAndIndex(context.Context, *BatchEmbedAndIndexReq) (*BatchEmbedAndIndexResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchEmbedAndIndex not implemented")
}
func (UnimplementedCognevraServiceServer) BatchWriteGraph(context.Context, *BatchWriteGraphReq) (*BatchWriteGraphResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchWriteGraph not implemented")
}
func (UnimplementedCognevraServiceServer) ParallelWriteDataPoints(context.Context, *ParallelWriteReq) (*ParallelWriteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ParallelWriteDataPoints not implemented")
}
func (UnimplementedCognevraServiceServer) SearchByText(context.Context, *SearchByTextReq) (*SearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchByText not implemented")
}
func (UnimplementedCognevraServiceServer) BatchSearchByText(context.Context, *BatchSearchByTextReq) (*BatchSearchByTextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchSearchByText not implemented")
}
func (UnimplementedCognevraServiceServer) GraphRead(context.Context, *GraphReadReq) (*GraphReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphRead not implemented")
}
func (UnimplementedCognevraServiceServer) GraphCompletionSearch(context.Context, *GraphCompletionSearchReq) (*GraphCompletionSearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphCompletionSearch not implemented")
}
func (UnimplementedCognevraServiceServer) PipelineCognify(*PipelineCognifyReq, grpc.ServerStreamingServer[PipelineCognifyProgress]) error {
	return status.Error(codes.Unimplemented, "method PipelineCognify not implemented")
}
func (UnimplementedCognevraServiceServer) LLMCacheGet(context.Context, *LLMCacheGetReq) (*LLMCacheGetResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LLMCacheGet not implemented")
}
func (UnimplementedCognevraServiceServer) LLMCachePut(context.Context, *LLMCachePutReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LLMCachePut not implemented")
}
func (UnimplementedCognevraServiceServer) LLMCacheStats(context.Context, *Empty) (*LLMCacheStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LLMCacheStats not implemented")
}
func (UnimplementedCognevraServiceServer) SemanticDedup(context.Context, *SemanticDedupReq) (*SemanticDedupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SemanticDedup not implemented")
}
func (UnimplementedCognevraServiceServer) MultiQuerySearch(context.Context, *MultiQuerySearchReq) (*MultiQuerySearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MultiQuerySearch not implemented")
}
func (UnimplementedCognevraServiceServer) IngestData(context.Context, *IngestDataReq) (*IngestDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestData not implemented")
}
func (UnimplementedCognevraServiceServer) ExtractText(context.Context, *ExtractTextReq) (*ExtractTextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractText not implemented")
}
func (UnimplementedCognevraServiceServer) TemporalSearch(context.Context, *TemporalSearchReq) (*TemporalSearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TemporalSearch not implemented")
}
func (UnimplementedCognevraServiceServer) BM25Index(context.Context, *BM25IndexReq) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BM25Index not implemented")
}
func (UnimplementedCognevraServiceServer) BM25Search(context.Context, *BM25SearchReq) (*BM25SearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BM25Search not implemented")
}
func (UnimplementedCognevraServiceServer) HybridSearch(context.Context, *HybridSearchReq) (*HybridSearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HybridSearch not implemented")
}
func (UnimplementedCognevraServiceServer) Compact(context.Context, *Empty) (*CompactResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Compact not implemented")
}
func (UnimplementedCognevraServiceServer) mustEmbedUnimplementedCognevraServiceServer() {}
func (UnimplementedCognevraServiceServer) testEmbeddedByValue()                         {}

// UnsafeCognevraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CognevraServiceServer will
// result in compilation errors.
type UnsafeCognevraServiceServer interface {
	mustEmbedUnimplementedCognevraServiceServer()
}

func RegisterCognevraServiceServer(s grpc.ServiceRegistrar, srv CognevraServiceServer) {
	// If the following call panics, it indicates UnimplementedCognevraServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CognevraService_ServiceDesc, srv)
}

func _CognevraService_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).CreateCollection(ctx, req.(*CreateCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_DropCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).DropCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_DropCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).DropCollection(ctx, req.(*DropCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).ListCollections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_HasCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).HasCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_HasCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).HasCollection(ctx, req.(*HasCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).Insert(ctx, req.(*InsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_BatchInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).BatchInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_BatchInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).BatchInsert(ctx, req.(*BatchInsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_ChunkText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkTextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).ChunkText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_ChunkText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).ChunkText(ctx, req.(*ChunkTextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).GetByID(ctx, req.(*GetByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_ProcessTriplets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessTripletsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).ProcessTriplets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_ProcessTriplets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).ProcessTriplets(ctx, req.(*ProcessTripletsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_HashFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).HashFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_HashFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).HashFiles(ctx, req.(*HashFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_ListDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).ListDirectory(ctx, req.(*ListDirectoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_AggregateSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).AggregateSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_AggregateSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).AggregateSearch(ctx, req.(*AggregateSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_SearchTriplets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTripletsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).SearchTriplets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_SearchTriplets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).SearchTriplets(ctx, req.(*SearchTripletsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_DeduplicateGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeduplicateGraphReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).DeduplicateGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_DeduplicateGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).DeduplicateGraph(ctx, req.(*DeduplicateGraphReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_BatchEmbedAndIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchEmbedAndIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).BatchEmbedAndIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_BatchEmbedAndIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).BatchEmbedAndIndex(ctx, req.(*BatchEmbedAndIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_BatchWriteGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchWriteGraphReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).BatchWriteGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_BatchWriteGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).BatchWriteGraph(ctx, req.(*BatchWriteGraphReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_ParallelWriteDataPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParallelWriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).ParallelWriteDataPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_ParallelWriteDataPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).ParallelWriteDataPoints(ctx, req.(*ParallelWriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_SearchByText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchByTextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).SearchByText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_SearchByText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).SearchByText(ctx, req.(*SearchByTextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_BatchSearchByText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSearchByTextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).BatchSearchByText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_BatchSearchByText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).BatchSearchByText(ctx, req.(*BatchSearchByTextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_GraphRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).GraphRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_GraphRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).GraphRead(ctx, req.(*GraphReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_GraphCompletionSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphCompletionSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).GraphCompletionSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_GraphCompletionSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).GraphCompletionSearch(ctx, req.(*GraphCompletionSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_PipelineCognify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineCognifyReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CognevraServiceServer).PipelineCognify(m, &grpc.GenericServerStream[PipelineCognifyReq, PipelineCognifyProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognevraService_PipelineCognifyServer = grpc.ServerStreamingServer[PipelineCognifyProgress]

func _CognevraService_LLMCacheGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLMCacheGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).LLMCacheGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_LLMCacheGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).LLMCacheGet(ctx, req.(*LLMCacheGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_LLMCachePut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLMCachePutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).LLMCachePut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_LLMCachePut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).LLMCachePut(ctx, req.(*LLMCachePutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_LLMCacheStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).LLMCacheStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_LLMCacheStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).LLMCacheStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_SemanticDedup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticDedupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).SemanticDedup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_SemanticDedup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).SemanticDedup(ctx, req.(*SemanticDedupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_MultiQuerySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiQuerySearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).MultiQuerySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_MultiQuerySearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).MultiQuerySearch(ctx, req.(*MultiQuerySearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_IngestData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).IngestData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_IngestData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).IngestData(ctx, req.(*IngestDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_ExtractText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractTextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).ExtractText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_ExtractText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).ExtractText(ctx, req.(*ExtractTextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_TemporalSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemporalSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).TemporalSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_TemporalSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).TemporalSearch(ctx, req.(*TemporalSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_BM25Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BM25IndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).BM25Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_BM25Index_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).BM25Index(ctx, req.(*BM25IndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_BM25Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BM25SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).BM25Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_BM25Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).BM25Search(ctx, req.(*BM25SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_HybridSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HybridSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).HybridSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_HybridSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).HybridSearch(ctx, req.(*HybridSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognevraService_Compact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognevraServiceServer).Compact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognevraService_Compact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognevraServiceServer).Compact(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CognevraService_ServiceDesc is the grpc.ServiceDesc for CognevraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CognevraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cognevra.v1.CognevraService",
	HandlerType: (*CognevraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _CognevraService_CreateCollection_Handler,
		},
		{
			MethodName: "DropCollection",
			Handler:    _CognevraService_DropCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _CognevraService_ListCollections_Handler,
		},
		{
			MethodName: "HasCollection",
			Handler:    _CognevraService_HasCollection_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _CognevraService_Insert_Handler,
		},
		{
			MethodName: "BatchInsert",
			Handler:    _CognevraService_BatchInsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CognevraService_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _CognevraService_Search_Handler,
		},
		{
			MethodName: "ChunkText",
			Handler:    _CognevraService_ChunkText_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _CognevraService_Info_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _CognevraService_GetByID_Handler,
		},
		{
			MethodName: "ProcessTriplets",
			Handler:    _CognevraService_ProcessTriplets_Handler,
		},
		{
			MethodName: "HashFiles",
			Handler:    _CognevraService_HashFiles_Handler,
		},
		{
			MethodName: "ListDirectory",
			Handler:    _CognevraService_ListDirectory_Handler,
		},
		{
			MethodName: "AggregateSearch",
			Handler:    _CognevraService_AggregateSearch_Handler,
		},
		{
			MethodName: "SearchTriplets",
			Handler:    _CognevraService_SearchTriplets_Handler,
		},
		{
			MethodName: "DeduplicateGraph",
			Handler:    _CognevraService_DeduplicateGraph_Handler,
		},
		{
			MethodName: "BatchEmbedAndIndex",
			Handler:    _CognevraService_BatchEmbedAndIndex_Handler,
		},
		{
			MethodName: "BatchWriteGraph",
			Handler:    _CognevraService_BatchWriteGraph_Handler,
		},
		{
			MethodName: "ParallelWriteDataPoints",
			Handler:    _CognevraService_ParallelWriteDataPoints_Handler,
		},
		{
			MethodName: "SearchByText",
			Handler:    _CognevraService_SearchByText_Handler,
		},
		{
			MethodName: "BatchSearchByText",
			Handler:    _CognevraService_BatchSearchByText_Handler,
		},
		{
			MethodName: "GraphRead",
			Handler:    _CognevraService_GraphRead_Handler,
		},
		{
			MethodName: "GraphCompletionSearch",
			Handler:    _CognevraService_GraphCompletionSearch_Handler,
		},
		{
			MethodName: "LLMCacheGet",
			Handler:    _CognevraService_LLMCacheGet_Handler,
		},
		{
			MethodName: "LLMCachePut",
			Handler:    _CognevraService_LLMCachePut_Handler,
		},
		{
			MethodName: "LLMCacheStats",
			Handler:    _CognevraService_LLMCacheStats_Handler,
		},
		{
			MethodName: "SemanticDedup",
			Handler:    _CognevraService_SemanticDedup_Handler,
		},
		{
			MethodName: "MultiQuerySearch",
			Handler:    _CognevraService_MultiQuerySearch_Handler,
		},
		{
			MethodName: "IngestData",
			Handler:    _CognevraService_IngestData_Handler,
		},
		{
			MethodName: "ExtractText",
			Handler:    _CognevraService_ExtractText_Handler,
		},
		{
			MethodName: "TemporalSearch",
			Handler:    _CognevraService_TemporalSearch_Handler,
		},
		{
			MethodName: "BM25Index",
			Handler:    _CognevraService_BM25Index_Handler,
		},
		{
			MethodName: "BM25Search",
			Handler:    _CognevraService_BM25Search_Handler,
		},
		{
			MethodName: "HybridSearch",
			Handler:    _CognevraService_HybridSearch_Handler,
		},
		{
			MethodName: "Compact",
			Handler:    _CognevraService_Compact_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PipelineCognify",
			Handler:       _CognevraService_PipelineCognify_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/cognevra.proto",
}
