// levara_v2.proto — next-generation Levara gRPC API (T10).
//
// Design goals:
//   1. Fix the naming drift that made v1 confusing (Insert vs Add vs Save
//      vs Create). v2 keeps Insert as the canonical write and exposes
//      Add/Save/Create as `deprecated=true` aliases so clients can migrate
//      one RPC at a time — per 20.04-tasks.md D12.
//   2. Introduce a typed ErrorDetail so clients can distinguish validation
//      errors from auth errors from backend errors without parsing the
//      status message string.
//   3. Reserve field numbers in every message so renaming a field later
//      doesn't accidentally reuse a wire tag that older clients still know.
//
// v1 stays active for 3 months post-v2-launch (D11). Both services are
// registered on the same port; a v2-aware client picks its flavour via
// the service name, a v1 client sees v2 as not-implemented.
//
// This file is authored but NOT yet code-generated in this commit. Run
// `make proto` once protoc-gen-go is wired into CI; in the meantime the
// file serves as the reviewable contract.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: levara_v2.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LevaraServiceV2_Insert_FullMethodName      = "/levara.v2.LevaraServiceV2/Insert"
	LevaraServiceV2_Add_FullMethodName         = "/levara.v2.LevaraServiceV2/Add"
	LevaraServiceV2_Save_FullMethodName        = "/levara.v2.LevaraServiceV2/Save"
	LevaraServiceV2_Create_FullMethodName      = "/levara.v2.LevaraServiceV2/Create"
	LevaraServiceV2_BatchInsert_FullMethodName = "/levara.v2.LevaraServiceV2/BatchInsert"
	LevaraServiceV2_Delete_FullMethodName      = "/levara.v2.LevaraServiceV2/Delete"
	LevaraServiceV2_Search_FullMethodName      = "/levara.v2.LevaraServiceV2/Search"
	LevaraServiceV2_Info_FullMethodName        = "/levara.v2.LevaraServiceV2/Info"
)

// LevaraServiceV2Client is the client API for LevaraServiceV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LevaraServiceV2Client interface {
	// Records — canonical.
	Insert(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*InsertResp, error)
	// Deprecated: Do not use.
	// Records — aliases. All three delegate to Insert on the server. Left
	// in place for v1 migration so clients who built around Add/Save/Create
	// don't have to rename their generated code on day one.
	Add(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*InsertResp, error)
	// Deprecated: Do not use.
	Save(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*InsertResp, error)
	// Deprecated: Do not use.
	Create(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*InsertResp, error)
	BatchInsert(ctx context.Context, in *BatchInsertReq, opts ...grpc.CallOption) (*BatchInsertResp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	// Info — public, not auth-gated.
	Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
}

type levaraServiceV2Client struct {
	cc grpc.ClientConnInterface
}

func NewLevaraServiceV2Client(cc grpc.ClientConnInterface) LevaraServiceV2Client {
	return &levaraServiceV2Client{cc}
}

func (c *levaraServiceV2Client) Insert(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*InsertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResp)
	err := c.cc.Invoke(ctx, LevaraServiceV2_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *levaraServiceV2Client) Add(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*InsertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResp)
	err := c.cc.Invoke(ctx, LevaraServiceV2_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *levaraServiceV2Client) Save(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*InsertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResp)
	err := c.cc.Invoke(ctx, LevaraServiceV2_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *levaraServiceV2Client) Create(ctx context.Context, in *InsertReq, opts ...grpc.CallOption) (*InsertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResp)
	err := c.cc.Invoke(ctx, LevaraServiceV2_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levaraServiceV2Client) BatchInsert(ctx context.Context, in *BatchInsertReq, opts ...grpc.CallOption) (*BatchInsertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInsertResp)
	err := c.cc.Invoke(ctx, LevaraServiceV2_BatchInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levaraServiceV2Client) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, LevaraServiceV2_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levaraServiceV2Client) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, LevaraServiceV2_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levaraServiceV2Client) Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResp)
	err := c.cc.Invoke(ctx, LevaraServiceV2_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LevaraServiceV2Server is the server API for LevaraServiceV2 service.
// All implementations must embed UnimplementedLevaraServiceV2Server
// for forward compatibility.
type LevaraServiceV2Server interface {
	// Records — canonical.
	Insert(context.Context, *InsertReq) (*InsertResp, error)
	// Deprecated: Do not use.
	// Records — aliases. All three delegate to Insert on the server. Left
	// in place for v1 migration so clients who built around Add/Save/Create
	// don't have to rename their generated code on day one.
	Add(context.Context, *InsertReq) (*InsertResp, error)
	// Deprecated: Do not use.
	Save(context.Context, *InsertReq) (*InsertResp, error)
	// Deprecated: Do not use.
	Create(context.Context, *InsertReq) (*InsertResp, error)
	BatchInsert(context.Context, *BatchInsertReq) (*BatchInsertResp, error)
	Delete(context.Context, *DeleteReq) (*DeleteResp, error)
	Search(context.Context, *SearchReq) (*SearchResp, error)
	// Info — public, not auth-gated.
	Info(context.Context, *InfoReq) (*InfoResp, error)
	mustEmbedUnimplementedLevaraServiceV2Server()
}

// UnimplementedLevaraServiceV2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLevaraServiceV2Server struct{}

func (UnimplementedLevaraServiceV2Server) Insert(context.Context, *InsertReq) (*InsertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedLevaraServiceV2Server) Add(context.Context, *InsertReq) (*InsertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedLevaraServiceV2Server) Save(context.Context, *InsertReq) (*InsertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedLevaraServiceV2Server) Create(context.Context, *InsertReq) (*InsertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedLevaraServiceV2Server) BatchInsert(context.Context, *BatchInsertReq) (*BatchInsertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInsert not implemented")
}
func (UnimplementedLevaraServiceV2Server) Delete(context.Context, *DeleteReq) (*DeleteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLevaraServiceV2Server) Search(context.Context, *SearchReq) (*SearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedLevaraServiceV2Server) Info(context.Context, *InfoReq) (*InfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedLevaraServiceV2Server) mustEmbedUnimplementedLevaraServiceV2Server() {}
func (UnimplementedLevaraServiceV2Server) testEmbeddedByValue()                         {}

// UnsafeLevaraServiceV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LevaraServiceV2Server will
// result in compilation errors.
type UnsafeLevaraServiceV2Server interface {
	mustEmbedUnimplementedLevaraServiceV2Server()
}

func RegisterLevaraServiceV2Server(s grpc.ServiceRegistrar, srv LevaraServiceV2Server) {
	// If the following call panics, it indicates UnimplementedLevaraServiceV2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LevaraServiceV2_ServiceDesc, srv)
}

func _LevaraServiceV2_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevaraServiceV2Server).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LevaraServiceV2_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevaraServiceV2Server).Insert(ctx, req.(*InsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevaraServiceV2_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevaraServiceV2Server).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LevaraServiceV2_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevaraServiceV2Server).Add(ctx, req.(*InsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevaraServiceV2_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevaraServiceV2Server).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LevaraServiceV2_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevaraServiceV2Server).Save(ctx, req.(*InsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevaraServiceV2_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevaraServiceV2Server).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LevaraServiceV2_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevaraServiceV2Server).Create(ctx, req.(*InsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevaraServiceV2_BatchInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevaraServiceV2Server).BatchInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LevaraServiceV2_BatchInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevaraServiceV2Server).BatchInsert(ctx, req.(*BatchInsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevaraServiceV2_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevaraServiceV2Server).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LevaraServiceV2_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevaraServiceV2Server).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevaraServiceV2_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevaraServiceV2Server).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LevaraServiceV2_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevaraServiceV2Server).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevaraServiceV2_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevaraServiceV2Server).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LevaraServiceV2_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevaraServiceV2Server).Info(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LevaraServiceV2_ServiceDesc is the grpc.ServiceDesc for LevaraServiceV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LevaraServiceV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levara.v2.LevaraServiceV2",
	HandlerType: (*LevaraServiceV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _LevaraServiceV2_Insert_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _LevaraServiceV2_Add_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _LevaraServiceV2_Save_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _LevaraServiceV2_Create_Handler,
		},
		{
			MethodName: "BatchInsert",
			Handler:    _LevaraServiceV2_BatchInsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _LevaraServiceV2_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _LevaraServiceV2_Search_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _LevaraServiceV2_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "levara_v2.proto",
}
